# VS code cũng đẹp mà
Tui yêu cái đẹp, thấy cái gì đẹp là tui lưu lại hết à
Tui muốn sản phẩm mk làm ra có sự chỉnh chu, áp dụng được vào thực tiễn, thực sự có ích cho đời

In [1]:
import random

# https://www.fileformat.info/info/unicode/category/So/list.htm

list = ['''Dừa lòng :)) \U0001F965''',
        '\U0001F335 \U0001F335 \U0001F335',
        'Tóc giả giả \U0001FAAD',
        '9094 -> Mồm\U0001F415 vó\U0001F434',
        'Kay \U0001F332 \U0001F333 \U0001F99D \U0001F423',
        'Tăng Phúc \U0001F9A6',
        '2 Neko \U0001F451 \U0001F40D \U0001F63A \U0001F638 \U0001F639 \U0001F640',
        'Nui \U0001F35C',
        'ST \U0001F43A \U0001F427', 
        '\U0001F33B', '\U0001F337', '\U0001F338', '\U0001F339', '\U0001F33A', '\U0001F33C', '\U0001F33E', '\U0001F340']
# print(*list, sep='\n')

random_item = (random.choice(list) + ' \u2740 '+ random.choice(list) + ' \u2740 '+random.choice(list) + ' \u2740 ' + '\n')*5
print(random_item)

2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ ST 🐺 🐧 ❀ 9094 -> Mồm🐕 vó🐴 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ ST 🐺 🐧 ❀ 9094 -> Mồm🐕 vó🐴 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ ST 🐺 🐧 ❀ 9094 -> Mồm🐕 vó🐴 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ ST 🐺 🐧 ❀ 9094 -> Mồm🐕 vó🐴 ❀
2 Neko 👑 🐍 😺 😸 😹 🙀 ❀ ST 🐺 🐧 ❀ 9094 -> Mồm🐕 vó🐴 ❀

In [2]:
# import libraries 

import numpy as np
import pandas as pd

#Vẽ biểu đồ
import matplotlib.pyplot as plt 

# Vẽ biểu đồ nhiệt
import seaborn as sns

from collections import Counter

# 1. EDA Basic Statisctic

In [3]:
# review file data
filename = r"E:\Chuyển từ download sang\A Học tập Bách Khoa\ĐA2\Đồ án 2 _ 2025\Project_full\Crawl_job\Data_raw\data_vietnamworks.csv"

df=pd.read_csv(filename)
df

,index,job_link,keyword,title,company,location,salary,date_posted,deadline_date,category,...,job_level,experience,education,hire_number,age,skills,is_urgent,description,requirements,benefits
0,1,https://www.vietnamworks.com/kiem-toan-vien-ki...,Data Analyst,Kiểm Toán Viên / Kiểm Toán Nội Bộ,Ngân Hàng Thương Mại TNHH MTV Ngoại Thương Côn...,Hà Nội,Thương lượng,27/03/2026,2026-04-26,Kiểm Toán,...,Nhân viên,3,Cử nhân,2,Không hiển thị,"Audit, Kiểm Toán, Kiểm Toán Viên Cao Cấp, Phân...",No,MÔ TẢ CÔNG VIỆC 1. Thực hiện công việc thuộc c...,Trình độ chuyên môn: Tốt nghiệp đại học chính ...,Đào tạo|Khác
1,2,https://www.vietnamworks.com/ky-su-phat-trien-...,Data Analyst,"Kỹ Sư Phát Triển Nền Tảng, Hệ Thống","Viện Phát Triển Chuyển Đổi Xanh, Chuyển Đổi Số...",Hà Nội,Thương lượng,27/03/2026,2026-04-26,Data Engineer/Data Analyst/AI,...,Nhân viên,Không hiển thị,Không giới hạn,Không hiển thị,Không hiển thị,"AI, Khoa Học Máy Tính, Kỹ Thuật Phần Mềm",No,"1) Tham gia thiết kế kiến trúc, phát triển chứ...","1) Tốt nghiệp đại học trở lên, chuyên ngành Kh...",Thưởng|Chăm sóc sức khoẻ
2,3,https://www.vietnamworks.com/chuyen-vien-cao-c...,Data Analyst,Chuyên Viên Cao Cấp Vận Hành Thương Hiệu Quốc Tế,Trang Văn hóa công ty,Hồ Chí Minh,Thương lượng,27/03/2026,2026-04-26,Tiếp Thị,...,Nhân viên,3,Cử nhân,Không hiển thị,Không hiển thị,"Quản Trị Hàng Hóa, Phân tích dữ liệu, Truyền t...",No,"Mục đích vị trí công việc Triển khai, theo dõi...",1. Bằng cấp: Đại học Chuyên ngành: QTKD/Market...,Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương
3,4,https://www.vietnamworks.com/nhan-vien-phat-tr...,Data Analyst,Nhân Viên Phát Triển Dự Án Nông Nghiệp (Agricu...,CÔNG TY TNHH MUYUAN VIỆT NAM,Hồ Chí Minh,16tr-30tr ₫/tháng,27/03/2026,2026-04-26,Nông/Lâm/Ngư nghiệp,...,Nhân viên,1,Cao đẳng,Không hiển thị,23-35,"Giao Tiếp Đàm Phán, Nghiên Cứu Môi Trường, Ngh...",No,Mô tả công việc: 1. Quan hệ chính phủ & kết nố...,Tốt nghiệp cao đẳng trở lên (ưu tiên ngành nôn...,Thưởng|Chăm sóc sức khoẻ|Đào tạo|Khác
4,5,https://www.vietnamworks.com/ie-engineer-20310...,Data Analyst,IE Engineer,CÔNG TY TNHH DỆT REGENT VIỆT NAM,Phú Thọ,Thương lượng,27/03/2026,2026-04-26,Thiết Kế Công Nghiệp/Kỹ Thuật,...,Nhân viên,2,Cử nhân,1,Không hiển thị,"Data Analysis, Industrial Engineering, Analysi...",No,POSITION SUMMARY We are recruiting an IE engin...,"KNOWLEDGE, SKILLS AND ABILITIES Bachelor's Deg...",Thưởng|Đào tạo|Khác
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2401,2402,https://www.vietnamworks.com/senior-supply-cha...,Business Intelligence,Senior Supply Chain Operation Executive,CÔNG TY TNHH BLUEZON GLOBAL,Hồ Chí Minh,25tr-35tr ₫/tháng,08/06/2026,2026-07-08,Quản Lý Chuỗi Cung Ứng,...,Nhân viên,2,Cử nhân,Không hiển thị,Không hiển thị,"Supply Chain Management, Logistics operations,...",No,1. Supply Planning & Inventory Monitoring Rece...,'- Education: Bachelor’s degree in Supply Chai...,Thưởng|Chăm sóc sức khoẻ|Đào tạo|Khác
2402,2403,https://www.vietnamworks.com/business-analyst-...,Business Intelligence,Business Analyst,CÔNG TY TNHH EZ TECH VIỆT NAM,Hà Nội,Thương lượng,08/06/2026,2026-07-08,Phân Tích Kinh Doanh/Phân Tích Hệ Thống,...,Nhân viên,2,Không giới hạn,1,Không hiển thị,"Phân tích nghiệp vụ, Tư duy logic, Tư Duy Hệ T...",No,"Làm việc với các bên liên quan để thu thập, ph...",Có tối thiểu 02 năm kinh nghiệm ở vị trí Busin...,Thưởng|Chăm sóc sức khoẻ|Đào tạo|Khác
2403,2404,https://www.vietnamworks.com/giam-doc-kinh-doa...,Business Intelligence,Giám Đốc Kinh Doanh | Sales Director | Thu Nhậ...,Công Ty CP Tập Đoàn Vinatech Việt Nam,Hà Nội,"$ 1,500-2,500 /tháng",08/06/2026,2026-07-08,Phân Tích Kinh Doanh/Phân Tích Hệ Thống,...,Giám Đốc và Cấp Cao Hơn,10,Cử nhân,Không hiển thị,37-50,"Sales & Business Development, Giám đốc kinh do...",No,1. Mục tiêu công việc: Chịu trách nhiệm xây dự...,Kinh nghiệm Tối thiểu 8 – 10 năm kinh nghiệm t...,Thưởng|Nghỉ phép có lương|Khác
2404,2405,https://www.vietnamworks.com/campaign-manageme...,Business Intelligence,Campaign Management Manager - Xanh Delivery (X...,GSM,Hồ Chí Minh,"$ 1,500-3,000 /tháng",26/05/2026,2026-06-25,Phân Tích Kinh Doanh/Phân Tích Hệ Thống,...,Trưởng phòng,Không yêu cầu,Không giới hạn,Không hiển thị,Không hiển thị,"SQL, Power BI, Tableu, PowerPoint",No,Mô tả công việc GSM đang phát triển Xanh Deliv...,"'- Tốt nghiệp Đại học (Marketing, Kinh doanh, ...",Thưởng|Chăm sóc sức khoẻ|Đào tạo
2405,2406,https://www.vietnamworks.com/business-analyst-...,Business Intelligence,Business Analyst Lead (Domain Chính Phủ - Chuy...,CÔNG TY CỔ PHẦN SYNODUS,Hà Nội,Tới 60tr ₫/tháng,20/05/2026,2026-06-19,Phân Tích Kinh Doanh/Phân Tích Hệ Thống,...,Nhân viên,5,Không giới hạn,8,24-40,"Analytical Thinking, Business Analysis, Conten...",No,Tham gia trao đổi với khách hàng để tìm hiểu v...,Lead: Từ 7 năm kinh nghiệm làm Business Analys...,Thưởng|Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhó...

In [4]:
# Kiểm tra kiểu dữ liệu
df.dtypes

index             int64
job_link         object
keyword          object
title            object
company          object
location         object
salary           object
date_posted      object
deadline_date    object
category         object
field            object
job_type         object
job_level        object
experience       object
education        object
hire_number      object
age              object
skills           object
is_urgent        object
description      object
requirements     object
benefits         object
dtype: object

In [6]:
# Thống kê các cột chứa giá trị text

# percentile list
perc = [.25, .50, .75]
  
# list of dtypes to include
include = ['object']
  
# calling describe method
desc = df.describe(percentiles=perc, include=include)
  
# display
desc

,job_link,keyword,title,company,location,salary,date_posted,deadline_date,category,field,...,job_level,experience,education,hire_number,age,skills,is_urgent,description,requirements,benefits
count,1646,1646,1646,1618,1645,1646,1646,1646,1644,1646,...,1646,1646,1646,1646,1646,1646,1646,1644,1645,1646
unique,1646,15,1431,665,96,233,71,66,105,48,...,5,13,7,12,103,1381,2,1387,1409,331
top,https://www.vietnamworks.com/kiem-toan-vien-ki...,Data Analyst,Business Analyst,Trang Văn hóa công ty,Hà Nội,Thương lượng,25/03/2026,2026-05-31,Data Engineer/Data Analyst/AI,Phần Mềm CNTT/Dịch vụ Phần mềm,...,Nhân viên,3,Cử nhân,Không hiển thị,Không hiển thị,"SAP, Consulting, Information Technology, SAP C...",No,Các phúc lợi dành cho bạn Thưởng 13th monthly ...,Các phúc lợi dành cho bạn Thưởng 13th monthly ...,Thưởng|Chăm sóc sức khoẻ|Khác
freq,1,1152,13,492,677,1091,47,83,321,183,...,1204,387,1176,920,1209,6,1547,8,8,106

In [7]:
# Đếm số giá trị duy nhất từng cột
df.nunique()

index            1646
job_link         1646
keyword            15
title            1431
company           665
location           96
salary            233
date_posted        71
deadline_date      66
category          105
field              48
job_type            7
job_level           5
experience         13
education           7
hire_number        12
age               103
skills           1381
is_urgent           2
description      1387
requirements     1409
benefits          331
dtype: int64

In [ ]:
# Cột Keyword có bao nhiêu giá trị duy nhất
df['keyword'].unique().tolist()

['Data Analyst',
 'Business Intelligence',
 'Data Visualization',
 'Product Analyst',
 'Data Engineer',
 'ETL',
 'Analytics Engineer',
 'Cloud Data',
 'Machine Learning',
 'AI Engineer',
 'Algorithm Engineer',
 'Database Administrator',
 'Marketing Analyst',
 'Data Warehouse',
 'NLP Engineer']

In [10]:
# Cột location có bao nhiêu giá trị duy nhất
df['location'].unique().tolist()

['Hà Nội',
 'Hồ Chí Minh',
 'Phú Thọ',
 'Hồ Chí Minh, Hà Nội',
 'Tây Ninh',
 'Hà Nội, Hồ Chí Minh',
 'Long An, Tây Ninh',
 'Đà Nẵng',
 'Hà Nội, Thái Nguyên',
 'Bắc Ninh',
 'Hồ Chí Minh, Bình Dương',
 'Đà Nẵng, Thừa Thiên Huế +1',
 'Hưng Yên, Hà Nội',
 'Ninh Bình',
 'Ninh Thuận, Hà Nội',
 'Đồng Nai',
 'Bình Dương',
 'Bắc Giang, Bắc Ninh',
 'Vĩnh Phúc',
 'Bình Dương, Hồ Chí Minh',
 'Lào Cai, Thái Nguyên +1',
 'Bà Rịa - Vũng Tàu',
 'Thừa Thiên Huế, Thái Nguyên',
 'Bắc Giang',
 'Hồ Chí Minh, Cần Thơ',
 'Hà Nội, Hồ Chí Minh +1',
 'Thái Nguyên, Hà Nội +1',
 'Ninh Bình, Hà Nam',
 'Hà Nội, Hải Dương',
 'Kiên Giang',
 'Đồng Nai, Hồ Chí Minh',
 'Bà Rịa - Vũng Tàu, Hồ Chí Minh',
 'Cần Thơ',
 'Bình Thuận',
 'Thừa Thiên Huế',
 'Thanh Hóa, Nghệ An +1',
 'Hưng Yên',
 'Long An',
 'Ninh Thuận',
 'Quốc tế',
 'Hà Nam, Long An +1',
 'Hà Nội, Hưng Yên',
 'Hải Phòng',
 'Lâm Đồng, Gia Lai +1',
 'Gia Lai, Khánh Hòa +1',
 'Hồ Chí Minh, Đồng Nai',
 'Hải Dương, Hà Nội',
 'Vĩnh Phúc, Hà Nội',
 'Bắc Ninh, Hà Nội',
 'Quảng Trị, Đà Nẵng +1',
 'Hòa Bình',
 'Lâm Đồng',
 'Ninh Bình, Hải Phòng +1',
 'Bắc Ninh, Hà Nội +1',
 'Tây Ninh, Bến Tre',
 'Bình Dương, Hồ Chí Minh +1',
 'Hưng Yên, Hải Dương +1',
 'Hà Nội, Bắc Ninh',
 'Hồ Chí Minh, Đà Nẵng +1',
 'Hà Nội, Thái Bình +1',
 'Hưng Yên, Hà Nội +1',
 'Hà Nam',
 'Hà Nội, Hải Dương +1',
 'Bắc Ninh, Bắc Giang +1',
 'Tây Ninh, Hồ Chí Minh',
 'Thanh Hóa, Hưng Yên +1',
 'Cần Thơ, Hà Nội',
 'An Giang',
 'Khác',
 'Hà Nội, Bà Rịa - Vũng Tàu',
 'Phú Thọ, Hải Phòng +1',
 'Bình Dương, Đồng Nai +1',
 'Hà Nội, Đà Nẵng +1',
 'Hưng Yên, Bắc Ninh +1',
 'Hải Phòng, Hải Dương',
 'Quảng Ninh, Hải Phòng',
 'Hà Nội, Đồng Tháp +1',
 'Gia Lai',
 'Khánh Hòa',
 'Bắc Ninh, Hưng Yên +1',
 'Thừa Thiên Huế, Thái Nguyên +1',
 nan,
 'Hồ Chí Minh, Cà Mau',
 'Thanh Hóa',
 'Hòa Bình, Ninh Bình +1',
 'Thái Nguyên',
 'Nghệ An',
 'Hồ Chí Minh, Bà Rịa - Vũng Tàu',
 'Hà Nội, Bắc Giang',
 'Hà Nội, Hà Tĩnh',
 'Quảng Trị, Thanh Hóa +1',
 'Bà Rịa - Vũng Tàu, Đồng Nai',
 'Bình Định, Bình Dương',
 'Thừa Thiên Huế, Hồ Chí Minh',
 'Đà Nẵng, Quảng Bình +1',
 'Cần Thơ, Hồ Chí Minh',
 'Hà Nội, Hải Phòng']

In [11]:
# Cột salary có bao nhiêu giá trị duy nhất
df['salary'].unique().tolist()

['Thương lượng',
 '16tr-30tr ₫/tháng',
 '$ 1,145-1,526 /tháng',
 '25tr-45tr ₫/tháng',
 '15tr-20tr ₫/tháng',
 '9tr-11tr ₫/tháng',
 '8tr-13tr ₫/tháng',
 '$ 350-550 /tháng',
 'Từ $ 800 /tháng',
 '18tr-22tr ₫/tháng',
 '$ 1,582-3,436 /tháng',
 '$ 1,000-2,000 /tháng',
 '18tr-20tr ₫/tháng',
 '25tr-35tr ₫/tháng',
 '11tr-14tr ₫/tháng',
 '25tr-40tr ₫/tháng',
 '30tr-45tr ₫/tháng',
 '9tr-15tr ₫/tháng',
 '18tr-25tr ₫/tháng',
 '$ 1,000-1,500 /tháng',
 '12tr-15tr ₫/tháng',
 '$ 550-800 /tháng',
 '10tr-12tr ₫/tháng',
 '16tr-18tr ₫/tháng',
 '8tr-10tr ₫/tháng',
 '20tr-40tr ₫/tháng',
 '8tr-12tr ₫/tháng',
 'Tới $ 5,000 /tháng',
 'Tới 40tr ₫/tháng',
 'Tới $ 7,000 /tháng',
 '50tr-70tr ₫/tháng',
 '10tr-15tr ₫/tháng',
 '$ 500-550 /tháng',
 '20tr-35tr ₫/tháng',
 'Tới 50tr ₫/tháng',
 '10tr-20tr ₫/tháng',
 'Từ $ 400 /tháng',
 '$ 300-300 /tháng',
 '36tr-86tr ₫/tháng',
 '$ 650-850 /tháng',
 '40tr-70tr ₫/tháng',
 'Từ 20tr ₫/tháng',
 '30tr-50tr ₫/tháng',
 '$ 450-1,000 /tháng',
 '$ 3,000-3,500 /tháng',
 '$ 1,000-1,000 /tháng',
 'Từ 25tr ₫/tháng',
 '12tr-17tr ₫/tháng',
 '$ 1,200-1,700 /tháng',
 '$ 800-1,500 /tháng',
 '$ 20tr-25tr /tháng',
 '20tr-25tr ₫/tháng',
 '$ 13tr-17tr /tháng',
 '200tr-500tr ₫/năm',
 '200tr-700tr ₫/năm',
 'Từ $ 600 /tháng',
 '$ 800-1,300 /tháng',
 '20tr-30tr ₫/tháng',
 '15tr-25tr ₫/tháng',
 '10tr-25tr ₫/tháng',
 '35tr-45tr ₫/tháng',
 '7tr-10tr ₫/tháng',
 '$ 700-1,100 /tháng',
 '$ 1,000-3,000 /tháng',
 '$ 500-1,500 /tháng',
 '20tr-50tr ₫/tháng',
 '$ 2,000-2,600 /tháng',
 '$ 800-1,000 /tháng',
 '$ 1,300-1,800 /tháng',
 '13tr-23tr ₫/tháng',
 '20tr-45tr ₫/tháng',
 '$ 460-575 /tháng',
 'Từ 15tr ₫/tháng',
 '$ 500-800 /tháng',
 '$ 700-900 /tháng',
 '15tr-30tr ₫/tháng',
 '50tr-80tr ₫/tháng',
 '$ 10tr-30tr /tháng',
 '$ 1,000-1,400 /tháng',
 '50tr-60tr ₫/tháng',
 'Từ 18tr ₫/tháng',
 '10tr-14tr ₫/tháng',
 '30tr-40tr ₫/tháng',
 '17tr-20tr ₫/tháng',
 'Tới $ 1,000 /tháng',
 '13tr-22tr ₫/tháng',
 '12tr-20tr ₫/tháng',
 '12tr-18tr ₫/tháng',
 'Từ 30tr ₫/tháng',
 'Từ 50tr ₫/tháng',
 '$ 2,000-3,000 /tháng',
 '36tr-72tr ₫/tháng',
 '26tr-40tr ₫/tháng',
 '60tr-160tr ₫/tháng',
 '$ 800-1,200 /tháng',
 '$ 350-650 /tháng',
 '14tr-18tr ₫/tháng',
 'Tới 60tr ₫/tháng',
 'Tới $ 2,500 /tháng',
 '35tr-40tr ₫/tháng',
 '28tr-35tr ₫/tháng',
 '$ 600-1,000 /tháng',
 '40tr-50tr ₫/tháng',
 '$ 2,000-3,500 /tháng',
 'Tới 45tr ₫/tháng',
 '$ 400-600 /tháng',
 '15tr-40tr ₫/tháng',
 '$ 500-700 /tháng',
 'Tới $ 10,000 /tháng',
 '$ 600-900 /tháng',
 '40-50 ₫/tháng',
 'Từ $ 2,000 /tháng',
 'Từ 35tr ₫/tháng',
 '14tr-20tr ₫/tháng',
 '13tr-14tr ₫/tháng',
 '16tr-20tr ₫/tháng',
 '22tr-35tr ₫/tháng',
 '13tr-18tr ₫/tháng',
 '22tr-25tr ₫/tháng',
 '22tr-28tr ₫/tháng',
 '$ 700-1,000 /tháng',
 '30tr-35tr ₫/tháng',
 '13tr-15tr ₫/tháng',
 'Tới 35tr ₫/tháng',
 '25tr-55tr ₫/tháng',
 '$ 1,500-2,000 /tháng',
 'Tới $ 2,000 /tháng',
 '$ 500-1,000 /tháng',
 'Tới $ 3,000 /tháng',
 '$ 750-1,200 /tháng',
 '$ 600-1,500 /tháng',
 '$ 1,200-3,500 /tháng',
 'Tới 30tr ₫/tháng',
 '$ 1,000-1,600 /tháng',
 'Từ 40tr ₫/tháng',
 '20tr-38tr ₫/tháng',
 '$ 1,000-2,500 /tháng',
 'Từ 60tr ₫/tháng',
 '¥ 350,000-450,000 /tháng',
 '$ 500-650 /tháng',
 '$ 900-1,000 /tháng',
 '$ 3,000-5,000 /tháng',
 'Từ $ 900 /tháng',
 '$ 500-900 /tháng',
 '$ 200-400 /tháng',
 '13tr-25tr ₫/tháng',
 'Tới $ 1,500 /tháng',
 '40tr-60tr ₫/tháng',
 '$ 800-1,100 /tháng',
 '20tr-70tr ₫/tháng',
 '$ 1,500-3,900 /tháng',
 '35tr-55tr ₫/tháng',
 '$ 600-1,200 /tháng',
 '$ 1,000-1,300 /tháng',
 '$ 700-1,500 /tháng',
 '$ 1,800-2,000 /tháng',
 'Tới 70tr ₫/tháng',
 '30tr-70tr ₫/tháng',
 '16.101tr-35tr ₫/tháng',
 'Từ 594.114tr ₫/năm',
 '$ 650-800 /tháng',
 '15tr-18tr ₫/tháng',
 '20tr-22tr ₫/tháng',
 '$ 2,200-2,800 /tháng',
 '$ 1,200-1,600 /tháng',
 '8tr-16tr ₫/tháng',
 '¥ 15tr-20tr /tháng',
 '$ 400-700 /tháng',
 '$ 700-1,300 /tháng',
 '$ 1,200-1,800 /tháng',
 '$ 1,100-1,800 /tháng',
 '10tr-18tr ₫/tháng',
 'S$ 700-800 /tháng',
 '$ 200-200 /tháng',
 '$ 450-550 /tháng',
 '$ 400-1,000 /tháng',
 '14tr-17tr ₫/tháng',
 '$ 1,600-1,600 /tháng',
 'Từ 11tr ₫/tháng',
 '$ 100-1,600 /tháng',
 '$ 400-500 /tháng',
 'Tới 20tr ₫/tháng',
 '$ 200-300 /tháng',
 'Tới $ 2,700 /tháng',
 'Tới $ 4,000 /tháng',
 '$ 1,500-2,200 /tháng',
 '15tr-23tr ₫/tháng',
 '$ 1,500-1,800 /tháng',
 '15tr-17tr ₫/tháng',
 '11tr-15tr ₫/tháng',
 '$ 350-450 /tháng',
 '$ 1,200-1,500 /tháng',
 '11tr-13tr ₫/tháng',
 '18tr-27tr ₫/tháng',
 '$ 100-1,000 /tháng',
 '$ 800-1,400 /tháng',
 'Từ $ 3,000 /tháng',
 '$ 800-2,000 /tháng',
 '13tr-20tr ₫/tháng',
 'Từ $ 500 /tháng',
 '50tr-150tr ₫/tháng',
 '24tr-30tr ₫/tháng',
 '250tr-400tr ₫/năm',
 'Từ 17tr ₫/tháng',
 '14tr-19tr ₫/tháng',
 'Từ $ 37tr /tháng',
 '$ 600-800 /tháng',
 '$ 2,000-2,400 /tháng',
 '12tr-16tr ₫/tháng',
 '25tr-30tr ₫/tháng',
 '28tr-34tr ₫/tháng',
 '$ 1,000-1,200 /tháng',
 '4,000-6,000 ₫/tháng',
 '40tr-100tr ₫/tháng',
 '$ 1,200-2,200 /tháng',
 'Từ 19tr ₫/tháng',
 '3tr-3tr ₫/tháng',
 '19tr-25tr ₫/tháng',
 '18tr-30tr ₫/tháng',
 '28tr-52tr ₫/tháng',
 '$ 400-550 /tháng',
 '$ 500-600 /tháng',
 '$ 50tr-70tr /tháng',
 '$ 2,500-7,000 /tháng',
 '22tr-30tr ₫/tháng',
 '20tr-33tr ₫/tháng',
 '15tr-22tr ₫/tháng',
 '600-1,200 ₫/tháng',
 '4tr-14tr ₫/tháng',
 '$ 1,500-2,500 /tháng',
 '35tr-60tr ₫/tháng',
 '17tr-35tr ₫/tháng',
 '$ 600-10,000 /tháng']

In [12]:
# Cột category có bao nhiêu giá trị duy nhất
df['category'].unique().tolist()

['Kiểm Toán',
 'Data Engineer/Data Analyst/AI',
 'Tiếp Thị',
 'Nông/Lâm/Ngư nghiệp',
 'Thiết Kế Công Nghiệp/Kỹ Thuật',
 'Bán Hàng Kỹ Thuật',
 'Quản Lý Chuỗi Cung Ứng',
 'Tiếp Thị Trực Tuyến',
 'Hoạch Định & Quản Lý Sản Xuất',
 'Quản Lý Kho & Phân Phối',
 'Tiếp Thị Nội Dung',
 'Hành Chính',
 'Quản Lý Cấp Cao',
 'Trợ Lý Kinh Doanh',
 'Chuyển Đổi Số',
 'Phân Tích & Báo Cáo Tài Chính',
 'Kinh Doanh Thương Mại, Cho Thuê & Quản Lý Tài Sản',
 'Dịch Vụ Sinh Viên/Hỗ Trợ Học Viên',
 'Bán Hàng/Phát Triển Kinh Doanh',
 'Khác',
 'Nghiên Cứu & Phân Tích Thị Trường',
 'Đảm Bảo Chất Lượng/Kiểm Soát Chất Lượng/Quản Lý Chất Lượng',
 'Kỹ Thuật Môi Trường',
 'Xuất Nhập Khẩu & Thủ Tục Hải Quan',
 'Quản Lý Đơn Hàng',
 'QA/QC/Software Testing',
 'Nhân Sự Tổng Hợp',
 'Công Nghệ Thực Phẩm',
 'Phân Tích Kinh Doanh/Phân Tích Hệ Thống',
 'Tuân Thủ & Kiểm Soát Rủi Ro',
 'Dịch Vụ Hỗ Trợ Khách Hàng',
 'Vận Hành Máy Móc',
 'Quản Trị Hiệu Suất & Sự Nghiệp',
 'Môi Giới & Giao Dịch Chứng Khoán',
 'Nghiên Cứu Học Thuật',
 'Quản Lý Dự Án Công Nghệ',
 'Kiểm Soát Viên Tài Chính',
 'UX/UI Design',
 'Tín Dụng',
 'Quản Lý Cơ Sở Vật Chất',
 'Lương Thưởng & Phúc Lợi',
 'Quản Lý Công Nghệ Thông Tin',
 'Kế Toán Tổng Hợp',
 'Quản Lý Dự Án',
 'Đầu Tư Tài Chính',
 'Kế Toán Tài Chính',
 'Thu Mua & Quản Trị Hàng Tồn Kho',
 'Phần Mềm Máy Tính',
 'Tuyển Dụng',
 'Phát Triển Bất Động Sản',
 'Dược Sĩ',
 'Tư Vấn Giáo Dục',
 'Quản Lý Thương Hiệu',
 'Kế Toán Thanh Toán',
 'Viễn Thông',
 'Kế Toán Quản Trị',
 'Tiếp Thị Thương Mại',
 'Quản Lý Khu Vực',
 'Quản Lý & Phát Triển Sản Phẩm',
 'Kế hoạch/Tư Vấn Doanh Nghiệp',
 'Bảo trì/Bảo Dưỡng',
 'Nghiên Cứu & Phát Triển',
 'Thư Ký',
 'Tư Vấn Rủi Ro',
 'Kỹ Thuật Điện/Điện Tử',
 'Quản Lý Cửa Hàng',
 'Dịch Vụ Khách Hàng',
 'Cơ Khí Tự Động Hoá',
 'Quản Lý Giáo Dục',
 'Kế Toán Thuế',
 'Đào Tạo Và Phát Triển',
 'Phân Tích Sản Xuất',
 'IT Support/Help Desk',
 'Quản Lý Sự Kiện',
 'Quản Lý Văn Phòng',
 'Bao Tiêu/Bảo Lãnh',
 'Phát Triển Dự Án/Đấu Thầu',
 'An Toàn Lao Động',
 'Phân Phối Dược Phẩm',
 'Bảo Mật Công Nghệ Thông Tin',
 'System/Cloud/DevOps Engineer',
 'Phân Tích Dự Án Bất Động Sản',
 'Phát Triển Sản Phẩm May Mặc',
 'Kỹ Thuật Ô Tô',
 'Giảng Dạy/Đào Tạo',
 'Quản Trị Cơ Sở Dữ Liệu',
 'Quản Lý Quan Hệ Khách Hàng',
 'Thiết Kế Nội Thất',
 'Xây Dựng',
 'Cơ Khí & Điện Lạnh',
 'Kỹ Thuật Hóa Học',
 'Vận Tải/Giao Nhận Hàng Hóa',
 'Điều Phối',
 'Quản Lý Tài Khoản Khách Hàng',
 'Thu Mua',
 'NGO/Phi Lợi Nhuận',
 'Khai Thác Mỏ',
 'Kế Toán Chi Phí',
 'Trợ Lý Bán Lẻ',
 'Quan Hệ Công Chúng',
 'Bán Hàng Qua Điện Thoại',
 'Định Phí Bảo Hiểm',
 'Chính sách, Quy hoạch & Quy định',
 nan,
 'Định Giá',
 'Kế Toán Công Nợ']

In [13]:
# Cột field có bao nhiêu giá trị duy nhất
df['field'].unique().tolist()

['Ngân hàng',
 'Hệ thống CNTT & Thiết bị',
 'Thời trang/Trang sức',
 'Nông nghiệp/Lâm nghiệp/Nuôi trồng thủy sản',
 'Sản xuất',
 'Điện/Điện tử',
 'Thương mại điện tử',
 'Nhập khẩu/Xuất khẩu',
 'Dịch vụ Y tế/Chăm sóc sức khỏe',
 'Làm đẹp (Mỹ phẩm) & Chăm sóc cá nhân',
 'Kỹ thuật xây dựng/Cơ sở hạ tầng',
 'Ô tô',
 'Tài Chính',
 'Dịch vụ lưu trú/Nhà hàng/Khách sạn/Du lịch',
 'Dệt may/May mặc/Giày dép',
 'Bất Động Sản/Cho thuê',
 'Giáo dục/Đào Tạo',
 'Phần Mềm CNTT/Dịch vụ Phần mềm',
 'Kế toán/Kiểm toán',
 'Bán lẻ/Bán sỉ',
 'Kiến trúc/Thiết kế nội thất',
 'Hàng tiêu dùng',
 'Dịch vụ môi trường/Chất thải',
 'Chứng khoán',
 'Khác',
 'Hậu cần/Giao nhận',
 'Cung cấp nhân lực',
 'Vận tải',
 'Vật liệu xây dựng',
 'Nghệ thuật/Giải trí',
 'Bảo hiểm',
 'Nội thất/Gỗ',
 'Truyền thông/Báo chí/Quảng cáo',
 'Dược phẩm',
 'Dịch vụ kho bãi',
 'Luật/Dịch vụ pháp lý',
 'Cơ khí/Máy móc/Thiết bị công nghiệp',
 'Hoá chất/Hoá sinh',
 'Nghiên cứu',
 'Tự động hoá',
 'Viễn thông',
 'Bao bì/In ấn/Dán nhãn',
 'Chuỗi cung ứng',
 'Chính phủ & NGO',
 'Sản xuất và Phân phối Điện/Khí đốt/Nước',
 'Thiết bị y tế',
 'Nhựa & Cao su',
 'Khai khoáng/Dầu khí']

In [14]:
# Cột job_type có bao nhiêu giá trị duy nhất
df['job_type'].unique().tolist()

['Toàn thời gian',
 'Thực tập',
 'Khác',
 'Hợp đồng thời vụ',
 'Nghề tự do',
 'Việc Làm Online',
 'Bán thời gian']

In [15]:
# Cột job_level có bao nhiêu giá trị duy nhất
df['job_level'].unique().tolist()

['Nhân viên',
 'Giám Đốc và Cấp Cao Hơn',
 'Trưởng phòng',
 'Mới Tốt Nghiệp',
 'Thực tập sinh/Sinh viên']

In [ ]:
# Cột experience (năm kinh nghiệm) có bao nhiêu giá trị duy nhất
df['experience'].unique().tolist()

['3',
 'Không hiển thị',
 '1',
 '2',
 '5',
 'Không yêu cầu',
 '7',
 '4',
 '6',
 '8',
 '10',
 '12',
 '15']

In [17]:
# Cột education có bao nhiêu giá trị duy nhất
df['education'].unique().tolist()

['Cử nhân',
 'Không giới hạn',
 'Cao đẳng',
 'Trung học',
 'Khác',
 'Trung cấp',
 'Thạc Sĩ']

In [ ]:
# Cột hire_number có bao nhiêu giá trị duy nhất
df['hire_number'].unique().tolist()

['2', 'Không hiển thị', '1', '5', '6', '15', '50', '3', '4', '8', '10', '7']

In [19]:
# Cột age có bao nhiêu giá trị duy nhất
df['age'].unique().tolist()

['Không hiển thị',
 '23-35',
 '24-35',
 '30-45',
 '25-60',
 '25-50',
 '22-60',
 '22-23',
 '15-60',
 '40-100',
 '25-35',
 '23-40',
 '25-30',
 '26-39',
 '25-40',
 '27-35',
 '26-35',
 '22-35',
 '24-40',
 '21-23',
 '22-28',
 '24-38',
 '20-40',
 '24-60',
 '25-55',
 '26-45',
 '30-50',
 '22-30',
 'Dưới 100 tuổi',
 '29-34',
 '25-38',
 '18-30',
 '30-55',
 '35-50',
 '23-100',
 '35-45',
 '25-45',
 '20-34',
 '30-60',
 '29-41',
 '26-50',
 '30-40',
 '25-34',
 '26-34',
 '28-100',
 '22-50',
 '24-36',
 '22-40',
 '15-45',
 '30-38',
 '28-60',
 '28-40',
 '30-35',
 '21-29',
 '22-45',
 '30-39',
 '28-45',
 '23-30',
 '24-50',
 '27-40',
 '27-39',
 '22-25',
 'Dưới 35 tuổi',
 '26-40',
 '15-40',
 '18-100',
 '25-39',
 '18-35',
 '26-100',
 '22-100',
 '28-35',
 '35-60',
 '35-40',
 '29-40',
 '18-60',
 '20-23',
 '29-50',
 '20-60',
 '25-100',
 'Dưới 45 tuổi',
 '20-45',
 '28-50',
 '21-34',
 '21-50',
 '27-60',
 '22-27',
 '24-30',
 '20-22',
 '18-45',
 '15-50',
 '26-30',
 '20-35',
 '27-45',
 '20-30',
 '27-50',
 '26-60',
 '30-42',
 '32-45',
 '15-30',
 '30-36',
 '18-36',
 '37-50',
 '21-100']

In [20]:
# Cột skills có bao nhiêu giá trị duy nhất
df['skills'].unique().tolist()

['Audit, Kiểm Toán, Kiểm Toán Viên Cao Cấp, Phân Tích Dữ Liệu, Viết Báo Cáo',
 'AI, Khoa Học Máy Tính, Kỹ Thuật Phần Mềm',
 'Quản Trị Hàng Hóa, Phân tích dữ liệu, Truyền thông & Marketing, Marketing',
 'Giao Tiếp Đàm Phán, Nghiên Cứu Môi Trường, Nghiên Cứu Nông Nghiệp, Phân Tích Dữ Liệu, Tiếng Trung Giao Tiếp',
 'Data Analysis, Industrial Engineering, Analysis Tool, MS Office, Textile Engineering',
 'Communication, Data Analysis, Project Management, Solar Construction, Technical Engineering',
 'Data Analysis, Merchandising, Project Management, Supplier Management, Sourcing Management',
 'Digital Marketing, Data Analysis, Content Strategy, Facebook Ads, FMCG',
 'Kế Hoạch Sản Xuất, Phân tích dữ liệu, Production Planning, Supply Planning, Quản Lý Tồn Kho',
 'ISO, Phân Tích Dữ Liệu, Kiểm Soát Tồn Kho, Kiểm Soát Chi Phí, Lập Kế Hoạch Mua Hàng',
 'Dựng Video, Phân Tích Dữ Liệu, Sáng Tạo Nội Dung, Viết Kịch Bản, Quản Lý Nội Dung',
 'Campaign Management, Data Analysis, Digital Marketing Performance, Ecommerce Optimization, Project Management',
 'Luật Đấu Thầu, Phân Tích Dữ Liệu, Quản Lý Hồ Sơ, Soạn Thảo Hồ Sơ, Theo Dõi Hợp Đồng',
 'Báo Cáo Quản Trị, Giao Tiếp, Phân Tích Dữ Liệu, Quản Trị Doanh Nghiệp, Điều Phối',
 'Market Research, Data Analysis, Survey Design, Excel, Communication',
 'Quản Trị Khách Hàng, Quản Trị Hệ Thống ERP, Phân tích dữ liệu, Giải quyết vấn đề, Sales Admin',
 'Client Acquisition, Collaboration, Data Analysis, Digital Marketing, Project Management',
 'Communication Skills, Data Analysis, Patent Portfolio Analysis, Product Management, Vendor Management',
 'Digital Marketing, Data Analysis, Communication Skills, Goal Oriented, Interpreter, Interpreter, Interpreter, Interpreter, Interpreter',
 'Lean Principals, Data Analysis, Problem-solving, Microsoft Office, English Language Proficiency',
 'Data Analysis, Analytical Skills, English, Google Sheet, Google Sheet, Google Sheet',
 'Power BI, Data Analysis, Tableau, SQL',
 'SQL, Phân Tích Nghiệp Vụ, Phân Tích Dữ Liệu, Wireframe, Mockup',
 'Market Research, Presentation Skills, Data Analysis, Retail Leasing, Brand Communication Development',
 'Communication, Data Management, MS Excel, SQL, Technical Support',
 'Data Analysis, Problem-solving, Process Engineer, Quality System, Teamwork',
 'Business Administration, Marketing Development, Data Analysis, Communication, Strategic Agility',
 'NLP, Computer Vision, LLM, AI Agents, Generative AI',
 'Digital Marketing, Data Analysis, Campaign Management, Market Research, Analytical Thinking',
 'Bảo Hiểm, Giao Tiếp Xuất Sắc, Lãnh Đạo, Phân Tích Dữ Liệu, Quản Trị Đội Ngũ',
 'SAP, Consulting, Data Analysis, UAT',
 'TikTok Shop Operation, Data Analysis, Ecommerce Operations, E-commerce, Social Commerce',
 'Data Analysis, Fragrances, Market Trend Analysis, Marketing Management, Presentation Skills',
 'Quản Trị Rủi Ro, Lập Kế Hoạch, Phân tích dữ liệu, Đào Tạo Huấn Luyện, Tự Làm Chủ',
 'AI, AI, AI Development, Chatbot AI, Data Analytics, Machine Learning',
 'HACCP, Audit Nội Bộ, Giám Sát Chất Lượng, Phân Tích Dữ Liệu, Quản Lý Chất Lượng Nhà Máy',
 'Data Analysis, Media Design, Project Management, Solution Oriented, Stakeholder Coordination, Stakeholder Coordination, Stakeholder Coordination, Stakeholder Coordination, Stakeholder Coordination',
 'Project Management, Cost Estimation, Data Analysis, Negotiation Skills, Site Supervision',
 'Luật Xuất Nhập Khẩu, Hải Quan, Logistics, Phân Tích Dữ Liệu, Xuất Nhập Khẩu',
 'Python, NLP, Computer Vision, Machine Learning, Logical Thinking',
 'Communication, Data Analysis, Inventory Control, Microsoft Office, Warehouse Management',
 'Digital Marketing, SEO strategy, Data Analysis, IT Optimization, Critical Thinking',
 'Data Analysis, Material, Supplier Negotiation, Material',
 'Data Analysis, Banking, T24, SQL, Python',
 'Data Analysis, ERP, Industrial Engineering, Lean Manufacturing, Project Management',
 'SQL, Python, Hadoop, Data Management, Big Data',
 'Data Analysis, Ecommerce Background, English Communication, Project Management, Retail Operations',
 'SQL, Cân Đối Nguồn Vốn, Phân Tích Dữ Liệu Khách Hàng, Python, Power BI',
 '7 QC Tools, Communication, Data Analysis, ISO 9001, QA/ QC',
 'Data Analysis, Excel Proficiency, Livestream, Multitasking, Passion For Skincare',
 'Quản Lý Bán Hàng, Phát Triển Thị Trường, Huấn Luyện Nhân Viên, Phân tích dữ liệu, Lãnh Đạo',
 'Customs Regulation, Data Analysis, Logistics Management, Project Management, Customs Clearance',
 'Phát Triển Thị Trường, Kỹ Thuật Môi Trường, Quản Lý Năng Lượng, ISO 14064, Phân Tích Dữ Liệu',
 'Real Estate, Data Analysis, Presentation Skills, Market Research, Critical Thinking',
 'Key Account Management, Data Analysis, Trade Marketing, Sales Forecast, Communication',
 'Tài Chính, Kinh Tế Xây Dựng, Kiểm Toán Nội Bộ, Phân Tích Dữ Liệu, Quản Trị Rủi Ro',
 'Compensation & Benefits, Data Analysis, Talent Management, HR, HRBP',
 'Product Development, Data Analysis, Basic Scientific Skills, Analytical Thinking, Animal Nutrition',
 'Sales Planning, Sales Analysis, Incentive Systems, Sales Strategy, Data Analysis',
 'Data Analysis, Digital Marketing, Social Commerce',
 'SQL, Power BI, Tableau, Oracle, Phân Tích Dữ Liệu Khách Hàng',
 'Data structuring, English fluency, ERP, Logical Thinking',
 'Data Analysis, Data Science, FRMS, Model Performance Analysis, Modeling',
 'Banking, Data Analysis, Financial Modeling, Model Performance Verification, Model Testing',
 'Banking, Credit Risk Modeling, Data Analysis, Python, SQL',
 'Giao Tiếp, Phân Tích Dữ Liệu, Quản Lý Hiệu Suất, Quản Trị Rủi Ro, Thuyết Trình',
 'Giao Tiếp, Kinh Doanh, Phân Tích Dữ Liệu, Quản Trị Rủi Ro, Xây Dựng Báo Cáo',
 'Business Intelligence, Marketing Analytics, Data Analysis, Communication, Strategy Consulting',
 'Data Analysis, Facebook Ads, Google Ads, Shopee Ads, Shopee Ads, Tiktok Shop',
 'Data-driven mindset, eCommerce, eCommerce, Sales Planning, Data Analysis, Data Analysis  (Excel, Power BI...)',
 'Supply Chain Management, Procurement, Data Analysis  (Excel, Power BI...), Stakeholder Mangement, Procurement Policy Compliance',
 'FPGA Development Boards, Digital Signal Processor, Embedded Software, Software Defined Radio, Messaging Systems',
 'Digital Marketing, Google Ads, Facebook Ads, Data Analysis, Content Marketing',
 'Analytical Skills, BigQuery, Google Data Studio, MariaDB, Python',
 'Active Mindset, Data Analysis, Facebook Ads, Local Market Development, Marketing Development',
 'Microsoft Power Platform, Automated Manufacturing, Azure AI Cloud, AI',
 'AI/ML, C/C++, Deep Learning Framework, NLP, Python',
 'Communication English, Corporate Governance, Leadership, Legal Compliance, Communication English',
 'NLP, Python, AI/ML, C/C++, Deep Learning Framework',
 'C/C++, Generative AI, Generative AI, Generative AI, Generative AI, Generative AI',
 'Computer Vision, C/C++, NLP, Python, Rust Programming',
 'Phân Tích Dữ Liệu, Vận Hành Thiết Bị, SPI, Quản Lý Dây Chuyền Sản Xuất',
 'Giao Tiếp Tiếng Anh, Kế Hoạch Kinh Doanh, Phân Tích Dữ Liệu, Phát Triển Khách Hàng, Đàm Phán Hợp Đồng',
 'SQL, Power BI, Tableau, Pivot table, Power Query, Power Query',
 'Chính Sách Nhân Sự, HRBP, Phân Tích Dữ Liệu, Quản Trị Nhân Sự, Đánh Giá Hiệu Suất',
 'Phân Tích Dữ Liệu, Data Analysis',
 'Customer Satisfaction, Data Analysis, Market Analysis, Problem-solving, Sales Strategy',
 'Giao Dịch Chứng Khoán, Quy Trình Triển Khai, Nghiệp Vụ Đầu Tư, Phân tích dữ liệu, Luật',
 'Docker, AI, AI, Docker, Docker, GenAI, Python, RAG',
 'Nghiên Cứu Thị Trường, Phát Triển Thị Trường, Phân tích dữ liệu, Kinh Doanh Hàng Tiêu Dùng, Trung Thực',
 'ASO, SEO, Data Analysis, Data Visualization Tools',
 'Data Analysis, Global Marketing, Paid Ads, Performance Marketing, User Acquisition, User Acquisition',
 'Business Intelligence, Database Systems',
 'Game Design, Game Mobile, Phân Tích Dữ Liệu, Agile/Scrum Proficiency, Product Owner',
 'Financial Analysis, Budgeting, Performance Management, Data Analysis, Communication',
 'Performance Marketing, Data Analysis, Project Management, Team Management, Process Optimization',
 'Agile, Collaboration, Data Analysis, Product Management, User Experience Testing',
 'System Modeling, Data Analysis, Wastewater Treatment',
 'Data Analysis, Market Research, Planning Skills, Planning Skills, Retail Marketing, Trade Marketing',
 'Ngân hàng, Khách Hàng Doanh Nghiệp, Phân Tích Dữ Liệu, Quản Trị Rủi Ro, Tài Chính',
 'Phân Tích Dữ Liệu, Power BI, Process Engineer, Production Analysis, SQL',
 'Quy Định Quản Lý Chất Lượng, Tuân Thủ Quy Định, Cải Tiến Quy Trình Sản Xuất, Quản Lý Hệ Thống Chất Lượng, Dữ liệu & Phân tích',
 'Communication, Data Analysis, E-Commerce Logistics, Negotiation Skills, Online Business',
 'Operation, Management, P&L Management, Negotiation, Data Analysis',
 'Kỹ năng giao tiếp, Kỹ năng giao tiếp, Phân Tích Dữ Liệu, Quản Lý Nhân Sự, Quản Trị Nhân Sự, Xây Dựng Chính Sách',
 'Digital Marketing, Facebook Ads, Tiktok Ads, Data Analysis, Online Marketing',
 'C/C++ Programming, Deep Learning, Deep Learning, Deep Learning, Python, PyTorch, TensorFlow',
 'Communication, Data Analysis, Employee Relation, HR Strategy, Talent Management',
 'Công Nghệ Thông Tin, Khoa Học Máy Tính, Lãnh Đạo, Phân Tích Dữ Liệu, Quy Trình Công Nghệ',
 'Kế Toán Tổng Hợp, Phân tích dữ liệu, Phần mềm kế toán, Giải quyết vấn đề, Bút Toán',
 'Data Analysis, International Trade, Leadership, Project Management, Supply Chain Management',
 'Quản Lý Dự Án, Xây Dựng Quy Trình, Theo Dõi Tồn Kho, Phân tích dữ liệu, Giao Tiếp',
 'Data Analysis, International Trade, Project Management, Strategic Thinking, Supply Chain Management',
 'Sales Admin, Sales Administration, Data Entry, Data Input Skills, Sales Coordination',
 'Phân Tích Dữ Liệu, Phát Triển Sản Phẩm, Product Owner, Superset, Superset, Superset, Superset, Superset, Superset, Đầu Tư Chứng Khoán',
 'Data Analysis, Demand Analysis, Demand Supply Planning, Inventory Management, Replenishment Planning',
 'Communication, Data Analysis, Organization Development, Performance Management, Talent Management',
 'Big Data Analytics, Team Management, Power BI, SQL, Data Analysis',
 'kho, Logistics, Phân Tích Dữ Liệu, Quản Lý Dự Án',
 'Giao Tiếp, Kế Toán, Kiểm Toán, Phân Tích Dữ Liệu, Tài Chính',
 'Digital Marketing Planning, Data Analysis, Presentation Skills, Healthcare Industry, pharmaceutical',
 'Supply Planning, Supply Planning, Inventory Management, Data Analysis, Stakeholder Management',
 'Giao Tiếp, Lập Trình PLC, Phân Tích Dữ Liệu, Thiết Kế Điện, Tự Động Hóa',
 'Information Technology, Data Analysis, Communication, Digital Management, Digital Management, Digital Management',
 'Marketing Strategy, Digital Marketing, Data Analysis, Leadership, Marketing manager',
 'Communication, Data Analysis, Logistics, MS Excel, Project Management',
 'Communication Skills, Data Analysis, Financial Modeling, Layout Design, Local Logistics Operation',
 'Data Science, Git, NoSQL, NoSQL, Problem-solving, Python',
 'Content Creation, Creative Writing, Data Analysis, Digital Marketing, Seo',
 'Automation Engineering, Data Mart, Data Pipeline, Data Science, Teamwork',
 'Sales Development, Electronics, PCB, Sales, Technical Sales',
 'Customer Care, Data Analysis, Franchise Business Development, Market Analysis, Teamwork',
 'Ai/Ml Solution Design, Solution Architecture, Technical Lead, Technical Manager',
 'Chiến Lược Kinh Doanh, Nghiên Cứu Thị Trường, Phân Tích Dữ Liệu, Quản Lý Kinh Doanh, Thương Mại Quốc Tế',
 'Data Analysis, Data reporting, Python, SQL',
 'Business Intelligence, Ngân Hàng Số, Phân Tích Dữ Liệu, Phân Tích Kinh Doanh, Tài Chính Kế Toán',
 'Collaboration, Data Analysis, Problem Solving, Product Development, SQL',
 'Collaboration, Data Analysis, ERP Systems, Excel Skills, Supply Chain Management',
 'communication, Data Analysis, Visualization, Finance',
 'Data Analysis, Demand Planning, Demand Planning, Demand Planning, Forecasting, Supply Chain Management, Supply Planning',
 'Quality Management, CSR Compliance, Data Analysis, English Communication, Quality Assurance',
 'Python, Machine Learning Engineering, AI Engineer, Ai/Ml Engineering, DevOps & CI/CD',
 'SAP Analytics Cloud, SAP BW, SAP Cloud, SAP CPI',
 'Tiếng Nhật, Automation, Phân Tích Dữ Liệu, BPO, Excel',
 'Machine Learning, Data Science, Cloud Platforms, Python, SQL',
 'Cloud Platforms, Python, SQL, CoreData, Data Architecture',
 'Leadership, Data Science, Machine Learning, Communication Skills, Optimisation',
 'Alation, Collibra, Data Management, Stakeholder Management, Data Governance',
 'Kinh Doanh, Phân tích dữ liệu, Giao Tiếp, Lãnh Đạo, Quản Trị Khách Hàng',
 'Quản Lý Rủi Ro Tín Dụng, Phân Tích Tài Chính, Phân tích dữ liệu, Analysis BI, Phân Tích Tài Chính Vĩ Mô',
 'Audit, Data Analysis, Financial Risk Analysis, Budgetary Control',
 'Data Analysis, Communication Skills, Digital Marketing, Market Research, Product Marketing',
 'CPA, Data Analysis, Google Analytics, Performance Marketing, E commerce',
 'AI application, Data Analysis, Leadership, Product Management, Strategic Thinking',
 'Digital Banking, Quản Lý Quy Trình, Tiếng Anh, Triển Khai Dự Án, Ứng Dụng Công Nghệ Số',
 'AI, AI, Machine Learning Frameworks, Optimization, Optimization, Optimization, Optimization, Optimization',
 'Data Analys, Interpretation, Ltv Calculation, Marketing Analytics, Ga4 Proficiency',
 'Fintech, AI, AI, Data Architecture, Fraud Risks Management, Ml/Ai Frameworks',
 'Communication, Data Analysis, Recruitment Tasks, Stakeholder Management, Talent Acquisition',
 'performance marketing, Lead Generation, Data Analysis, Digital Advertising, Problem Solving, Lead Generation, Lead Generation, Lead Generation',
 'SPI, Repair Maintenance, Phân Tích Dữ Liệu',
 'Performance Marketing, Phân Tích Dữ Liệu, Quản Lý Chiến Dịch, Quản Lý Thương Hiệu, Tư Duy Chiến Lược',
 'HRBP, Phân Tích Chiến Lược, Phân Tích Dữ Liệu, Quản Trị Nhân Lực, Tiếng Anh',
 'Data Analysis, Data Management, Information System, SQL, Ai Strategy',
 'Bất Động Sản cho thuê, Phân Tích Dữ Liệu, Phát Triển Dự Án, Quản Lý Tài Sản, Quản Trị Thông Tin',
 'Data Analysis, Marketing Analytics, Dashboard Design, Statistical Modeling, Collaboration',
 'C/C++ Programming, Computer Vision, Robotics, Deep Learning, Deep Learning, Deep Learning',
 'Python, SQL, Data Science, Data Modeling, Machine Learning',
 'Brand Development, Data Analysis, Effective Communication, Market Research, Teamwork',
 'Insight Analysis, Phân Tích Dữ Liệu, SME, SQL, Quản Trị Phân Khúc Sme',
 'Phân Tích Dữ Liệu, Data Analysis, Business Analysis, PowerBI Analysis, Excel Reporting',
 'Pharmacy, Dược Phẩm, Medical Science Liaison, Medical Research, Data Analysis',
 'Client Facing, Communication Skills, Data Analysis, Market Research, Proposal Writing',
 'Sales Administration, Commercial Billing, Data Analysis, Process Improvement, Customer Service',
 'AutoCAD, Microsoft Office, Thiết Kế Khuôn Dập, Phân Tích Dữ Liệu, Cơ Khí',
 'Sales Operation, Distributor System Management, Market Development, Data Analysis, Communication',
 'Kiểm Soát Kiểm Toán, Kiểm Toán Nội Bộ, Phân Tích Chiến Lược, Phân Tích Dữ Liệu, Quản Lý Rủi Ro',
 'Data Engineer, Python, Big Data, SQL, Data Management',
 'Change Management, Data Analysis, Financial services experience, HR Management, Relationship Building',
 'SQL, Power BI, Tableu, PowerPoint',
 'AWS, Azure, MongoDB, Oracle',
 'Cloud Security, Data Governance, Data Governance, Data Governance, Data Governance, Data Governance, Data Governance',
 'Data Science, Deep Learning, Keras, Deep Learning, Deep Learning',
 'Core Banking, DWH, Oracle Database, Power BI, SQL',
 'Data Governance',
 'Phân Tích Thị Trường, Nghiên Cứu và Phân Tích Dữ Liệu, Phát Triển Kinh Doanh, Đàm Phán, Giao Tiếp',
 'Quản Lý Kinh Doanh, Kế Hoạch Bán Hàng, Nghiên Cứu Thị Trường, Phân Tích Dữ Liệu, Tiếp thị',
 'Brand Management, Marketing Strategy, Data Analysis, Digital Marketing, Marketing Planning',
 'BI Tools, Business Analysis, Ecommerce Solution, Excel Skills, Multitasking',
 'Data reporting, Account Receivable, Data Analysis',
 'Communication, Data Analysis, Quality Control, Resolve Problem, Team Management',
 'Cloud Platforms, Databricks, Python, Scala, SQL',
 'Performance Management, HRM Software System, Data Analysis, Advance Excel',
 'Data Analysis, Information Security, IT Audit, Risk Assessment, Teamwork',
 'Category Management, Data Analysis, English Language Proficiency, Strategic Sourcing, Supplier Negotiation',
 'Analytical Skills, Communication, English Fluency, Excel, Microsoft Word',
 'Big Data, Data Visualization, Giải Quyết Vấn Đề, Phân Tích Dữ Liệu, SQL',
 'Coding Experience, Deep Learning, ESS Tools, Deep Learning, Deep Learning',
 'Big Data, Hadoop, Python, Spark, SQL',
 'Creative Problem Solving, Data Analysis, Machine Learning, Python Programming, Statistical Analysis',
 'AR Development, Data Analysis, Machine Learning, Python Programming, Nlp Techniques',
 'Data Analytics, Business Intelligence, Power BI, English Improvement, Data Visualization',
 'Bảo trì & bảo dưỡng máy móc',
 'Communication Skills, Data Analysis, Problem-solving, Project Management, Technical Thinking',
 'Giải Quyết Vấn Đề, Kỹ Năng Excel, Kỹ năng giao tiếp, Phân Tích Dữ Liệu, Kỹ năng giao tiếp',
 'Kỹ năng đàm phán, Phân Tích Chiến Lược, Phân Tích Dữ Liệu, Quản Lý Thời Gian, Xây Dựng Mối Quan Hệ',
 'Computer Vision, Transformer-Based Architectures, Python, Pytorch, Leadership',
 'Costing Analysis, BOM Calculation, 工艺流程工程师, ERP System, Data Analysis',
 'Phân Tích Dữ Liệu, Phân Tích Thị Trường, Phát Triển Kinh Doanh, Quản Lý Dự Án, Xây Dựng Kế Hoạch Bán Hàng',
 'Data Analysis, Business Support, Compliance Management, Hazard Control, Inventory Tracking',
 'Giải Quyết Vấn Đề, Giao Tiếp, Kế Toán, Phân Tích Dữ Liệu, Tài Chính',
 'Conversion Rate Optimization, Data Analysis, Digital Marketing, Performance Marketing, Team Management',
 'Data Engineering, Data Analysis, Python, VBA, PowerBI',
 'Azure SQL Database, Azure SQL Database, Azure SQL Database, Power Automate, Power BI, AI, AI, SQL',
 'SQL, Python, Data Visualization, Data Modeling, Data Analysis',
 'Amazon Web Services, Data Analysis, Photoshop, Ecommerce Background, Customer Mindset',
 'Quản Trị Nhân Sự, KPI Reporting, Đào Tạo, Phân tích dữ liệu, Giao Tiếp',
 'Agile, API, Phân Tích Dữ Liệu, Phân Tích Nghiệp Vụ, User Stories',
 'Digital Marketing, Google Ads, Facebook Ads, Data Analysis, Leadership',
 'Data Science, Computer Science, Python, SQL, Machine Learning',
 'Data Analysis, Excel, Information Systems, Information Systems, Information Systems, Information Systems, Power BI, Financial Products',
 'Nghiên Cứu Thị Trường, Consumer Insight, phân tích vĩ mô, Data Analysis, Strategic Planning',
 'LLM, Agentic Ai, GenAI, Multi-Agent Ai',
 'Data Analysis, Data Science, Python, Power BI, Minitab',
 'Business Analysis, Data AI, Digital & AI Tools, Kinh Doanh Quốc Tế, Marketing',
 'Quản Trị Dữ Liệu, Phân tích dữ liệu, Phân tích dữ liệu, Trí Tuệ Nhân Tạo, Lãnh Đạo',
 'API Integration, Data Modeling, database management, MongoDB, SQL',
 'Báo Cáo Tài Chính, Giao Tiếp, Kiểm Soát Nội Bộ, Kỹ năng tin học văn phòng, Phân Tích Dữ Liệu',
 'Planning Data Analysis, Financial Planning, Life Insurance',
 'Product Management, Sales Management, Supplier Management, Data Analysis, Communication',
 'Giao Tiếp Xuất Sắc, Kỹ năng lập kế hoạch, Phân Tích Chiến Lược, Phân Tích Dữ Liệu, Quản Lý Dự Án, Kỹ năng lập kế hoạch, Kỹ năng lập kế hoạch',
 'Data Analysis, Data Analytics, Microsoft Office, Risk Management, Sql Proficiency',
 'Customs Declare, Data Analysis, SQL, Excel, Customs Clearance',
 'Data Analysis, Logistics Optimization, Order Management, SAP, Vendor Management',
 'Kế Toán, Phân Tích Dữ Liệu, Produc manager, product owner, Quản Lý Tiến Độ Dự Án',
 'Communication Skills, Data Analysis, Market Research, Product Development, Risk Analysis',
 'Garment Technical Design, VSM, Line Balancing, Data Analysis, Team Management',

In [21]:
# Cột benefits có bao nhiêu giá trị duy nhất
df['benefits'].unique().tolist()

['Đào tạo|Khác',
 'Thưởng|Chăm sóc sức khoẻ',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Khác',
 'Thưởng|Đào tạo|Khác',
 'Khác',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Khác',
 'Chăm sóc sức khoẻ|Giải thưởng|Cơ hội du lịch|Khác',
 'Thưởng|Nghỉ phép có lương|Xe đưa đón',
 'Thưởng|Nghỉ phép có lương|Giải thưởng|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Máy tính xách tay|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch',
 'Thưởng|Chăm sóc sức khoẻ|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Căn-tin|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Đào tạo|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Căn-tin',
 'Chăm sóc sức khoẻ|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Nghỉ phép có lương|Đào tạo',
 'Chăm sóc sức khoẻ|Hoạt động nhóm|Khác',
 'Thưởng|Giải thưởng|Khác',
 'Máy tính xách tay|Hoạt động nhóm|Căn-tin',
 'Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Hoạt động nhóm',
 'Thưởng|Cơ hội du lịch|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Giải thưởng|Cơ hội du lịch|Khác',
 'Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm|Căn-tin|Khác',
 'Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng',
 'Thưởng|Chăm sóc sức khoẻ|Xe đưa đón',
 'Chăm sóc sức khoẻ|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Xe đưa đón|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Hoạt động nhóm',
 'Thưởng|Đào tạo|Giải thưởng',
 'Thưởng|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Khác',
 'Thưởng|Nghỉ phép có lương',
 'Thưởng',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Thư viện|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Máy tính xách tay',
 'Thưởng|Nghỉ phép có lương|Cơ hội du lịch',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Cơ hội du lịch|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Máy tính xách tay|Xe đưa đón',
 'Thưởng|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Nghỉ phép có lương|Giải thưởng|Khác',
 'Thưởng|Nghỉ phép có lương|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Máy tính xách tay',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Giải thưởng|Khác',
 'Thưởng|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo',
 'Thưởng|Đào tạo|Giải thưởng|Khác',
 'Chăm sóc sức khoẻ|Cơ hội du lịch|Khác',
 'Thưởng|Nghỉ phép có lương|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Giải thưởng',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Điện thoại',
 'Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Máy tính xách tay|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Cơ hội du lịch|Căn-tin',
 'Thưởng|Nghỉ phép có lương|Cơ hội du lịch|Hoạt động nhóm',
 'Nghỉ phép có lương|Khác',
 'Chăm sóc sức khoẻ|Giải thưởng|Khác',
 'Máy tính xách tay|Xe đưa đón|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Điện thoại|Cơ hội du lịch|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Máy tính xách tay|Khác',
 'Chăm sóc sức khoẻ',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Máy tính xách tay|Cơ hội du lịch',
 'Chăm sóc sức khoẻ|Xe đưa đón|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Xe đưa đón|Khác',
 'Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay',
 'Thưởng|Chăm sóc sức khoẻ|Cơ hội du lịch',
 'Đào tạo',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Hoạt động nhóm|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Căn-tin|Khác',
 'Thưởng|Đào tạo|Căn-tin',
 'Thưởng|Đào tạo|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Đào tạo',
 'Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Xe đưa đón|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Căn-tin|Khác',
 'Thưởng|Cơ hội du lịch|Xe đưa đón',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Căn-tin',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm',
 'Thưởng|Nghỉ phép có lương|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Máy tính xách tay',
 'Thưởng|Máy tính xách tay|Cơ hội du lịch',
 'Giải thưởng|Máy tính xách tay|Xe đưa đón|Phiếu giảm giá',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Khác',
 'Thưởng|Xe đưa đón|Khác',
 'Nghỉ phép có lương',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Hoạt động nhóm|Căn-tin',
 'Thưởng|Đào tạo|Máy tính xách tay|Khác',
 'Giải thưởng|Điện thoại',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Giải thưởng|Thư viện|Phiếu giảm giá|Khác',
 'Thưởng|Đào tạo|Cơ hội du lịch|Xe đưa đón|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Cơ hội du lịch|Hoạt động nhóm',
 'Thưởng|Đào tạo|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Xe đưa đón|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Xe đưa đón|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Xe đưa đón|Khác',
 'Đào tạo|Máy tính xách tay',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Căn-tin|Khác',
 'Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Nghỉ phép có lương|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Cơ hội du lịch|Hoạt động nhóm|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Khác',
 'Đào tạo|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Hoạt động nhóm|Khác',
 'Thưởng|Đào tạo|Giải thưởng|Hoạt động nhóm|Căn-tin|Khác',
 'Nghỉ phép có lương|Máy tính xách tay|Hoạt động nhóm',
 'Thưởng|Đào tạo|Cơ hội du lịch',
 'Chăm sóc sức khoẻ|Giải thưởng|Máy tính xách tay|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Xe đưa đón|Nhà trẻ',
 'Nghỉ phép có lương|Hoạt động nhóm|Xe đưa đón',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Thư viện|Phiếu giảm giá|Khác',
 'Chăm sóc sức khoẻ|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay',
 'Thưởng|Đào tạo|Hoạt động nhóm|Xe đưa đón|Căn-tin',
 'Thưởng|Nghỉ phép có lương|Giải thưởng|Khác',
 'Thưởng|Máy tính xách tay|Điện thoại|Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón|Căn-tin|Phiếu giảm giá|Nhà trẻ',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Khác',
 'Thưởng|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Hoạt động nhóm',
 'Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm|Xe đưa đón|Căn-tin|Khác',
 'Thưởng|Đào tạo|Hoạt động nhóm|Khác',
 'Thưởng|Hoạt động nhóm',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Hoạt động nhóm|Xe đưa đón|Căn-tin|Phiếu giảm giá',
 'Thưởng|Đào tạo',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Cơ hội du lịch',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Phiếu giảm giá',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Xe đưa đón|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Khác',
 'Nghỉ phép có lương|Máy tính xách tay|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Xe đưa đón|Khác',
 'Thưởng|Nghỉ phép có lương|Phiếu giảm giá',
 'Chăm sóc sức khoẻ|Đào tạo|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Căn-tin|Khác',
 'Đào tạo|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Điện thoại|Cơ hội du lịch|Căn-tin',
 'Thưởng|Đào tạo|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Hoạt động nhóm|Xe đưa đón|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Phiếu giảm giá|Khác',
 'Thưởng|Đào tạo|Máy tính xách tay',
 'Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Nhà trẻ|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Xe đưa đón',
 'Thưởng|Điện thoại|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Hoạt động nhóm|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Điện thoại|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Hoạt động nhóm',
 'Thưởng|Nghỉ phép có lương|Căn-tin',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Căn-tin',
 'Chăm sóc sức khoẻ|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Máy tính xách tay|Căn-tin',
 'Chăm sóc sức khoẻ|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Hoạt động nhóm|Xe đưa đón',
 'Chăm sóc sức khoẻ|Điện thoại|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Cơ hội du lịch|Khác',
 'Chăm sóc sức khoẻ|Máy tính xách tay|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Điện thoại|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Máy tính xách tay',
 'Thưởng|Giải thưởng|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Đào tạo|Xe đưa đón',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo',
 'Thưởng|Chăm sóc sức khoẻ|Hoạt động nhóm|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Hoạt động nhóm',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Cơ hội du lịch',
 'Thưởng|Chăm sóc sức khoẻ|Căn-tin|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Điện thoại|Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón|Phiếu giảm giá|Khác',
 'Chăm sóc sức khoẻ|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng',
 'Thưởng|Giải thưởng|Máy tính xách tay',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Căn-tin|Phiếu giảm giá',
 'Thưởng|Giải thưởng',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Xe đưa đón|Căn-tin',
 'Giải thưởng|Cơ hội du lịch|Khác',
 'Đào tạo|Căn-tin|Phiếu giảm giá|Khác',
 'Thưởng|Nghỉ phép có lương|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Xe đưa đón|Căn-tin',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Hoạt động nhóm|Căn-tin|Phiếu giảm giá|Khác',
 'Thưởng|Đào tạo|Giải thưởng|Nhà trẻ',
 'Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm|Khác',
 'Nghỉ phép có lương|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Hoạt động nhóm|Khác',
 'Thưởng|Cơ hội du lịch|Hoạt động nhóm',
 'Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm',
 'Đào tạo|Giải thưởng|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Phiếu giảm giá|Khác',
 'Chăm sóc sức khoẻ|Đào tạo|Giải thưởng',
 'Thưởng|Đào tạo|Xe đưa đón',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Nghỉ phép có lương|Máy tính xách tay',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Cơ hội du lịch|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Thư viện|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Giải thưởng|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Điện thoại|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Giải thưởng|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Đào tạo|Hoạt động nhóm|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Máy tính xách tay|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Cơ hội du lịch|Xe đưa đón|Khác',
 'Thưởng|Đào tạo|Cơ hội du lịch|Hoạt động nhóm',
 'Cơ hội du lịch|Khác',
 'Thưởng|Giải thưởng|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Máy tính xách tay|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Điện thoại|Hoạt động nhóm',
 'Thưởng|Chăm sóc sức khoẻ|Xe đưa đón|Căn-tin',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Nghỉ phép có lương|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Máy tính xách tay|Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón|Căn-tin|Phiếu giảm giá',
 'Thưởng|Nghỉ phép có lương|Máy tính xách tay|Khác',
 'Máy tính xách tay|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón|Căn-tin',
 'Chăm sóc sức khoẻ|Máy tính xách tay|Hoạt động nhóm|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay',
 'Thưởng|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Cơ hội du lịch',
 'Thưởng|Chăm sóc sức khoẻ|Giải thưởng|Cơ hội du lịch',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Cơ hội du lịch|Xe đưa đón|Căn-tin|Khác',
 'Thưởng|Máy tính xách tay|Cơ hội du lịch|Căn-tin',
 'Phiếu giảm giá',
 'Thưởng|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Giải thưởng|Máy tính xách tay|Cơ hội du lịch|Hoạt động nhóm|Căn-tin|Khác',
 'Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch|Hoạt động nhóm|Xe đưa đón|Khác',
 'Máy tính xách tay|Cơ hội du lịch|Căn-tin',
 'Chăm sóc sức khoẻ|Đào tạo|Cơ hội du lịch',
 'Chăm sóc sức khoẻ|Xe đưa đón|Khác',
 'Nghỉ phép có lương|Hoạt động nhóm|Khác',
 'Thưởng|Giải thưởng|Căn-tin',
 'Thưởng|Nghỉ phép có lương|Máy tính xách tay|Xe đưa đón',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Cơ hội du lịch',
 'Thưởng|Đào tạo|Cơ hội du lịch|Căn-tin|Khác',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nhà trẻ|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Thư viện|Phiếu giảm giá|Nhà trẻ',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Thư viện|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Đào tạo|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Giải thưởng|Máy tính xách tay|Điện thoại|Cơ hội du lịch|Hoạt động nhóm|Phiếu giảm giá',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Cơ hội du lịch|Căn-tin|Khác',
 'Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Máy tính xách tay|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Xe đưa đón',
 'Thưởng|Giải thưởng|Xe đưa đón',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Điện thoại|Phiếu giảm giá',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Giải thưởng|Điện thoại|Xe đưa đón|Khác',
 'Thưởng|Cơ hội du lịch',
 'Thưởng|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Cơ hội du lịch|Hoạt động nhóm',
 'Chăm sóc sức khoẻ|Đào tạo|Giải thưởng|Hoạt động nhóm|Khác',
 'Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Phiếu giảm giá|Khác',
 'Thưởng|Nghỉ phép có lương|Cơ hội du lịch|Hoạt động nhóm|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Máy tính xách tay|Căn-tin',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Xe đưa đón|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Thư viện|Máy tính xách tay|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Nghỉ phép có lương|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Căn-tin|Khác',
 'Thưởng|Chăm sóc sức khoẻ|Đào tạo|Máy tính xách tay|Hoạt động nhóm|Phiếu giảm giá|Khác',

In [ ]:
while 1==1:
    
    # Lời chào
    print("\n\U0001F4D0 WELCOME TO LENGTH CONVERTER \U0001F4D0\n")
    
    # Bước 1: Tạo danh mục, đối chiếu đơn vị đo
    dict_Length = {'meter':1, 'kilometer':0.001, 'centimeter':100, 'millimeter':1000, 'micrometer':10**6, 'nanometer':10**9 }
    
    
    # Bước 2: Nhập các biến đầu vào ________________________________________________________
    # Đơn vị user nhập, ko bị sai chính tả, ko phải đơn vị ngoài, ko dính lỗi in hoa
    # Value user nhập là number >= 0
    print('Available units of Length:                                      ') 
    print(*list(dict_Length.keys()), sep=", ")
    print('_____________________________\n')
    
    # Bước 2.1: nhập đơn vị đầu vào 
    while 1==1:
        unit_in = str(input('Enter starting unit of Length: ')).lower()
        if unit_in in list(dict_Length.keys()):
            break
        else:
            print(f"\n\u26A0 '{unit_in}' is not in available units list!")
            print(f'\u26A0 Please provide a available unit in list!')
    
    
    # Bước 2.1: nhập đơn vị đầu ra 
    while 1==1:
        unit_out = str(input('Enter unit of Length to convert to: ')).lower()
        if unit_in in list(dict_Length.keys()):
            break
        else:
            print(f"\n\u26A0 '{unit_in}' is not in available units list!")
            print(f'\u26A0 Please provide a available unit in list!')        
    
    
    #Bước 2.3: nhập giá trị muốn đổi
    while 1==1:
        try:
            value_in = float(input(f'Enter the value to convert in {unit_in}: '))
            if value_in < 0:
                print("\u26A0 Please enter a number >= 0!")
                continue
            break
        except Exception:
            print(f'\n\u26A0 Please provide a valid number!')
    
    
    # Bước 3: Tính toán & đưa ra kết quả ______________________________________________________
    value_out = value_in * dict_Length[unit_out] / dict_Length[unit_in]
    print(f'\nResult: {value_in} {unit_in} = {value_out} {unit_out}')
    
    # Bước 4: Hỏi user còn muốn chuyển đổi đơn vị tiếp ko ?
    print('_____________________________\n')
    key = str(input('\nDo you want to perform another conversion? (Y/N): ')).upper()
    if key == 'N':
        print("Thank you for using this Length Converter! \U0001F33B\n\n\n")
        break
    else: 
        print('\n\n\n')
        
        # 1 m =  0.001 km
        # 2 m = 2 * 0.001/1 km

📐 WELCOME TO LENGTH CONVERTER 📐

Available units of Length:
meter, kilometer, centimeter, millimeter, micrometer, nanometer
_____________________________

In [22]:
# Cột is_urgent có bao nhiêu giá trị duy nhất
df['is_urgent'].unique().tolist()

['No', 'Yes']

# 2. Clean draw data + Thống nhất tên + kiểu dữ liệu date

## 2.1. Format Date_posted

In [4]:
df['date_posted']

0       27/03/2026
1       27/03/2026
2       27/03/2026
3       27/03/2026
4       27/03/2026
           ...
2401    08/06/2026
2402    08/06/2026
2403    08/06/2026
2404    26/05/2026
2405    20/05/2026
Name: date_posted, Length: 2406, dtype: object

In [5]:
# 1. Chuyển cột date_posted sang định dạng datetime chuẩn của Pandas (nhận diện dd/mm/yyyy)
df['date_posted'] = pd.to_datetime(df['date_posted'], format='%d/%m/%Y', errors='coerce')

# 2. Đổi định dạng hiển thị sang yyyy-mm-dd (dạng chuỗi ký tự)
df['date_posted'] = df['date_posted'].dt.strftime('%Y-%m-%d')

# 3. Check lại
df['date_posted']

0       2026-03-27
1       2026-03-27
2       2026-03-27
3       2026-03-27
4       2026-03-27
           ...
2401    2026-06-08
2402    2026-06-08
2403    2026-06-08
2404    2026-05-26
2405    2026-05-20
Name: date_posted, Length: 2406, dtype: object

In [7]:
# Cột deadline_date có bao nhiêu giá trị duy nhất
df['deadline_date']

0       2026-04-26
1       2026-04-26
2       2026-04-26
3       2026-04-26
4       2026-04-26
           ...
2401    2026-07-08
2402    2026-07-08
2403    2026-07-08
2404    2026-06-25
2405    2026-06-19
Name: deadline_date, Length: 2406, dtype: object