# VS code cũng đẹp mà
Tui yêu cái đẹp, thấy cái gì đẹp là tui lưu lại hết à
Tui muốn sản phẩm mk làm ra có sự chỉnh chu, áp dụng được vào thực tiễn, thực sự có ích cho đời

In [1]:
import random

# https://www.fileformat.info/info/unicode/category/So/list.htm

list = ['''Dừa lòng :)) \U0001F965''',
        '\U0001F335 \U0001F335 \U0001F335',
        'Tóc giả giả \U0001FAAD',
        '9094 -> Mồm\U0001F415 vó\U0001F434',
        'Kay \U0001F332 \U0001F333 \U0001F99D \U0001F423',
        'Tăng Phúc \U0001F9A6',
        '2 Neko \U0001F451 \U0001F40D \U0001F63A \U0001F638 \U0001F639 \U0001F640',
        'Nui \U0001F35C',
        'ST \U0001F43A \U0001F427', 
        '\U0001F33B', '\U0001F337', '\U0001F338', '\U0001F339', '\U0001F33A', '\U0001F33C', '\U0001F33E', '\U0001F340']
# print(*list, sep='\n')

random_item = (random.choice(list) + ' \u2740 '+ random.choice(list) + ' \u2740 '+random.choice(list) + ' \u2740 ' + '\n')*5
print(random_item)

🌸 ❀ 🌷 ❀ Tóc giả giả 🪭 ❀
🌸 ❀ 🌷 ❀ Tóc giả giả 🪭 ❀
🌸 ❀ 🌷 ❀ Tóc giả giả 🪭 ❀
🌸 ❀ 🌷 ❀ Tóc giả giả 🪭 ❀
🌸 ❀ 🌷 ❀ Tóc giả giả 🪭 ❀

# EDA cơ bản 1

In [2]:
# import libraries 

import numpy as np
import pandas as pd

#Vẽ biểu đồ
import matplotlib.pyplot as plt 

# Vẽ biểu đồ nhiệt
import seaborn as sns

from collections import Counter

In [3]:
# review file data
filename = r"E:\Chuyển từ download sang\A Học tập Bách Khoa\ĐA2\Đồ án 2 _ 2025\Project_full\Crawl_job\Data_raw\data_itviec.csv"

df=pd.read_csv(filename)
df

,index,job_url,search_keyword,job_title,company_name,location,salary,is_fresher,job_type,date_post,job_skills,job_expertise,job_domain,company_industry,company_type,company_country,job_description,requirements,benefits,source_site
0,1,https://itviec.com/it-jobs/data-analyst-power-...,Data Analyst,Data Analyst/ Power BI Developer,CÔNG TY TNHH SOCOTEC VIỆT NAM,"17/575 Kim Mã, Ba Đình, Hà Nội, Ba Dinh, Ha Noi",20-25tr gross,No,At office,2026-04-05,"Data Analysis, Databricks, SQL, Data modeling,...",Data Analyst,Materials and Mining,Materials and Mining,IT Outsourcing,Vietnam,"Main Mission Within the Data & AI Hub, you wil...",Education Bachelor's or Master's degree (35 ye...,Attractive salary and bonus with annual revisi...,itviec.com
1,2,https://itviec.com/it-jobs/business-customer-d...,Data Analyst,Business Customer Data Analyst - Data Division,MB Bank,"Tòa nhà MB, số 18 Lê Văn Lương, Phường Yên Hòa...",You'll love it,No,At office,2026-04-04,"Data Analysis, Data Warehousing, ETL, Power BI...",Data Analyst,"Banking, Financial Services",Banking,IT Product,Vietnam,HO26.37 Chuyên viên Phân tích Khách hàng Doanh...,"Tốt nghiệp Đại học các chuyên ngành Thống kê, ...",Trải nghiệm Thu nhập hấp dẫn với gói đãi ngộ t...,itviec.com
2,3,https://itviec.com/it-jobs/data-analyst-power-...,Data Analyst,"Data Analyst (Power BI, MSSQL, Python)",S4BT Solutions for Business Travel.,"28 Mạc Đĩnh Chi, District 1, Ho Chi Minh",Up to 2800 usd,No,Hybrid,2026-04-02,"Data Analysis, Power BI, SQL, Agile, Python",Data Analyst,Software Products and Web Services,Software Products and Web Services,IT Product,France,"At Goelett by S4BT, we are a dynamic team pass...",Core Requirements: Strong proficiency in Power...,"A worklife balance: Hybrid working model, 15 d...",itviec.com
3,4,https://itviec.com/it-jobs/supply-chain-data-a...,Data Analyst,"Supply Chain Data Analyst (Total up-to 34,000 ...",Crossian,"Tầng 1, Tòa nhà Pax Sky, 63-65 phố Ngô Thì Nhậ...","Up-to 34,000 usd/year",No,At office,2026-04-02,"Data Analysis, Looker, Tableau, Power BI, English",Data Analyst,"E-commerce, Software Products and Web Services",E-commerce,IT Product,Vietnam,ABOUT THE ROLE Crossian is a highgrowth techno...,"Bachelor's degree in data science, Statistics,...","At Crossian, our people are the key to our suc...",itviec.com
4,5,https://itviec.com/it-jobs/data-analyst-sql-bi...,Data Analyst,"Data Analyst (SQL, BI tools) for Edtech project",CÔNG TY TNHH TEENUP,"Hà Nội: 61E Đê La Thành, phường Láng, Ha Noi",You'll love it,No,At office,2026-04-01,"Data Analysis, Microsoft Power Apps, SQL",Data Analyst,Education and Training,Education and Training,IT Product,Vietnam,"About TeenCare AI At TeenCare AI , we work at ...","2+ years in data, analytics, strategy, consult...","Compensation: Competitive, tied to impact Revi...",itviec.com
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1143,1144,https://itviec.com/it-jobs/junior-android-deve...,Database Administrator,Junior Android Developer (Kotlin/Java),Motorist Pte Ltd,"D003 chung cư Sadora , số 2, đường số 13, Phườ...",Very attractive!!!,Yes,At office,2026-06-12,"Android, Java, Database, OOP, Kotlin, English",Mobile Application Developer,Software Products and Web Services,Software Products and Web Services,IT Product,Singapore,We are looking for a Junior Android Developer ...,Technical Experiences Must Have ● Bachelor’s d...,● Competitive salary with annual performance r...,itviec.com
1144,1145,https://itviec.com/it-jobs/junior-ios-mobile-d...,Database Administrator,"Junior iOS Mobile Developer (Swift, English)",Motorist Pte Ltd,"D003 chung cư Sadora , số 2, đường số 13, Phườ...",Very attractive!!!,Yes,At office,2026-06-12,"iOS, API, Database, OOP, Swift, English",Mobile Application Developer,Software Products and Web Services,Software Products and Web Services,IT Product,Singapore,1. Education ● Bachelor’s degree in Computer S...,Technical Experiences Must Have ● Bachelor’s d...,● Competitive salary with annual performance r...,itviec.com
1145,1146,https://itviec.com/it-jobs/senior-backend-deve...,Database Administrator,"Senior Backend Developer (Java Spring Boot, BPM)",Bolt Tech,"Tầng 8, Tòa nhà Hapro Building, 11B Cát Linh, ...",Very attractive!!!,No,At office,2026-06-12,"Java, Solution Architecture, Database, SQL, Sp...",Backend Developer,IT Hardware and Computing,Software Products and Web Services,IT Product,Vietnam,Chúng tôi đang tìm kiếm Senior Backend Enginee...,Must Have Từ 5 năm kinh nghiệm phát triển Back...,Lương thỏa thuận Thưởng tháng 13 và thưởng hiệ...,itviec.com
1146,1147,https://itviec.com/it-jobs/senior-lead-fullsta...,Database Administrator,[Senior/ Lead] Fullstack Engineer,Crossian,"Tầng 1, Tòa nhà Pax Sky, 63-65 phố Ngô Thì Nhậ...",You'll love it,No,At office,2026-06-12,"Fullstack, Database, Python, NodeJS, JavaScrip...",Fullstack Developer,E-commerce,E-commerce,IT Product,Vietnam,Crossian is a highgrowth technologydriven ecom...,Education & Experience Education: Strong acade...,Ownership: Direct ownership of real work strea...,itviec.com
1147,1148,https://itviec.com/it-jobs/it-quality-control-...,Database Administrator,IT Quality Control (Tester),IDEAL LIFE JSC – IZIon24,"6th Floor, Phuong Long 2, 16 Nguyen Truong To,...",You'll love it,Yes,At office,2026-06-13,"Tester, API, QA QC, Database, Postman, SQL",Manual Tester,"Insurance, Banking, IT Services and IT Consult...",Retail and Wholesale,IT Product,Vietnam,Develop detailed test plans for each project/m...,Bachelor’s degree 1–2 years of experience in t...,13rd month bonus KPI Performance Bonus (based ...,itviec.com

In [4]:
# Kiểm tra kiểu dữ liệu
df.dtypes

index                int64
job_url             object
search_keyword      object
job_title           object
company_name        object
location            object
salary              object
is_fresher          object
job_type            object
date_post           object
job_skills          object
job_expertise       object
job_domain          object
company_industry    object
company_type        object
company_country     object
job_description     object
requirements        object
benefits            object
source_site         object
dtype: object

In [6]:
# Thống kê các cột chứa giá trị text

# percentile list
perc = [.25, .50, .75]
  
# list of dtypes to include
include = ['object']
  
# calling describe method
desc = df.describe(percentiles=perc, include=include)
  
# display
desc

,job_url,search_keyword,job_title,company_name,location,salary,is_fresher,job_type,date_post,job_skills,job_expertise,job_domain,company_industry,company_type,company_country,job_description,requirements,benefits,source_site
count,909,909,909,909,909,568,909,909,894,909,909,909,891,909,909,909,909,909,909
unique,909,15,813,415,545,104,2,10,81,849,66,221,34,5,26,818,812,592,1
top,https://itviec.com/it-jobs/data-analyst-power-...,Cloud Data,Senior AI Engineer,MB Bank,"Tòa nhà MB, số 18 Lê Văn Lương, Phường Yên Hòa...",You'll love it,No,At office,2026-04-04,"AI, LLM, Deep Learning, Machine Learning, Comp...",AI / Machine Learning Engineer,IT Services and IT Consulting,IT Services and IT Consulting,IT Product,Vietnam,"Phân tích yêu cầu nghiệp vụ, thiết kế và triển...",Tốt nghiệp Đại học trở lên Tối thiểu 5 năm kin...,Trải nghiệm Thu nhập hấp dẫn với gói đãi ngộ t...,itviec.com
freq,1,195,7,50,50,400,866,774,29,7,139,130,228,570,589,4,4,50,909

In [7]:
# Đếm số giá trị duy nhất từng cột
df.nunique()

index               909
job_url             909
search_keyword       15
job_title           813
company_name        415
location            545
salary              104
is_fresher            2
job_type             10
date_post            81
job_skills          849
job_expertise        66
job_domain          221
company_industry     34
company_type          5
company_country      26
job_description     818
requirements        812
benefits            592
source_site           1
dtype: int64

In [9]:
# Cột Keyword có bao nhiêu giá trị duy nhất
df['search_keyword'].unique().tolist()

['Data Analyst',
 'Business Intelligence',
 'Data Visualization',
 'Product Analyst',
 'Marketing Analyst',
 'Data Engineer',
 'ETL',
 'Cloud Data',
 'Machine Learning',
 'AI Engineer',
 'Database Administrator',
 'Data Quality Analyst',
 'Big Data Engineer',
 'Database Developer',
 'MLOps Engineer']

In [10]:
# Cột location có bao nhiêu giá trị duy nhất
df['location'].unique().tolist()

['17/575 Kim Mã, Ba Đình, Hà Nội, Ba Dinh, Ha Noi',
 'Tòa nhà MB, số 18 Lê Văn Lương, Phường Yên Hòa, Ha Noi',
 '28 Mạc Đĩnh Chi, District 1, Ho Chi Minh',
 'Tầng 1, Tòa nhà Pax Sky, 63-65 phố Ngô Thì Nhậm, Phường Phạm Đình Hổ, Hai Ba Trung, Ha Noi',
 'Hà Nội: 61E Đê La Thành, phường Láng, Ha Noi',
 '12th Floor, 68 Phan Dang Luu, Duc Nhuan Ward, Ho Chi Minh City, Ho Chi Minh',
 'The Capital Place, 29 Lieu Giai Street, Ngoc Ha Ward, Hanoi City, Vietnam, Ba Dinh, Ha Noi',
 'SMS Tower, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, Ho Chi Minh',
 '15th Floor, Taisei Square Hanoi, 289 Khuat Duy Tien street, Dai Mo Ward, Ha Noi, Cau Giay, Ha Noi',
 'Tầng 2, Số 56 Sunrise G, The Manor Central Park, Nguyễn Xiển, Đại Kim, Hoàng Mai, Hà Nội, Hoang Mai, Ha Noi',
 'REE Tower, 9 Doan Van Bo, Ward 12, District 4, Ho Chi Minh',
 '722 Điện Biên Phủ, Phường 22, Binh Thanh, Ho Chi Minh',
 '28 Mai Chí Thọ, An Phú, Quận 2, Thu Duc City, Ho Chi Minh',
 '19F, Coninco Tower 4 Tôn Thất Tùng, Dong Da, Ha Noi',
 '412 Nguyen Van Cu, Long Bien, Ha Noi',
 'Số 3, ngõ 98 Vũ Trọng Phụng, Thanh Xuan, Ha Noi',
 'Nam Ky Khoi Nghia, District 3, Ho Chi Minh',
 '122-124 Bàu Cát 2, Phường 12, Tan Binh, Ho Chi Minh',
 '442  Nguyễn Thị Minh Khai, District 3, Ho Chi Minh',
 '19 Duy Tan, Cau Giay, Ha Noi',
 'Tòa VOV, 35 Nguyễn Đình Chiểu, Hai Ba Trung, Ha Noi',
 '1060 Nguyen Van Linh, Tan Phong, District 7, Ho Chi Minh',
 'Waseco Building - 10 Pho Quang Street, Ward 02, Tan Binh, Ho Chi Minh',
 '7th Floor, Mach Building, 127 Ung Van Khiem, Binh Thanh, Ho Chi Minh',
 'Tầng 7, Tòa nhà Geleximco, 36 phố Hoàng Cầu, Ô Chợ Dừa, Dong Da, Ha Noi',
 '45 Nguyễn Văn Huyên, Cau Giay, Ha Noi',
 '235 Nguyễn Văn Cừ, District 1, Ho Chi Minh',
 '12A, Vietinbank building, 36 Tran Quoc Toan, Da Nang, Hai Chau, Da Nang',
 'Sailing Tower, 111A Pasteur, Ward Sai Gon, District 1, Ho Chi Minh',
 '20 Nguyen Dang Giai, District 2, Ho Chi Minh',
 '106 Nguyen Van Troi, Phu Nhuan, Ho Chi Minh',
 'Tầng 7, Tòa nhà Việt Á, 9 Duy Tân, Phường Cầu Giấy, Ha Noi',
 'Dong Loi Building, 1160 Lang Street, Lang Ward, Ha Noi, Dong Da, Ha Noi',
 '83 Ngo Thoi Nhiem St., Vo Thi Sau Ward, District 3, District 3, Ho Chi Minh',
 'Tầng 2,4 Lô III-26, Đường 19/5A, Nhóm CN III, Khu công nghiệp Tân Bình, Tan Phu, Ho Chi Minh',
 '273 Kim Mã – Hà Nội, Ba Dinh, Ha Noi',
 '163 Nguyễn Thị Nhung, KDC Vạn Phúc, Quốc lộ 13, Phường Hiệp Bình Phước, Thu Duc City, Ho Chi Minh',
 '324 Le Van Sy, Ward 2, Tan Binh, Ho Chi Minh',
 '9th Floor, Akuruhi Tower, 124 Tran Quang Khai, Tan Dinh, District 1, Ho Chi Minh',
 '3F, 94 Ho Nghinh Street, An Hai Ward, Da Nang',
 '10th Floor, VCN Tower, 2 To Huu Street (Onsite/Hybrid), Nha Trang, Khanh Hoa',
 'Phòng 305, tầng 3, 239 Xuân Thuỷ, Cau Giay, Ha Noi',
 'Orchard Parkview, 130 – 132 Hong Ha, Ward 9, Phu Nhuan, Ho Chi Minh',
 'MIOS Building, 121 Hoang Hoa Tham Street, Ward 7, Binh Thanh, Ho Chi Minh',
 '266 Đội Cấn, Ba Dinh, Ha Noi',
 'Landmark 72, E6 Pham Hung, Nam Tu Liem, Ha Noi',
 'Văn phòng đại diện tại Hà Nội: Toà nhà CT1 – C14 Bắc Hà, Đại Mỗ, Ha Noi',
 'Tòa ROX TOWER số 136 Hồ Tùng Mậu, Bac Tu Liem, Ha Noi',
 '36 Hoàng Cầu, Dong Da, Ha Noi',
 'Pearl 5 Tower, No.5 Le Quy Don Street, District 3, Ho Chi Minh',
 '6 Tân Cảng, Binh Thanh, Ho Chi Minh',
 'Tầng 5, Trụ sở chính của Tập đoàn Viettel, Lô D26, Khu đô thị mới Cầu Giấy, phường Yên Hòa, Cau Giay, Ha Noi',
 '364 Cong Hoa street, ward 13, Tan Binh, Ho Chi Minh',
 '51  Hoang Viet, Tan Binh, Ho Chi Minh',
 'Số 1, Phố Xốm, Phường Phú Lãm, Quận Hà Đông, Ha Noi',
 '34 Bạch Đằng, Phường Tân Sơn Hòa, Ho Chi Minh',
 '02 Tan Vien, ward 2, Tan Binh, Ho Chi Minh',
 'Tòa D’office Tổ 28 , Cau Giay, Ha Noi',
 'Vinacomin Tower, Số 3 Dương Đình Nghệ, Cau Giay, Ha Noi',
 'Tòa nhà Times Tower, Số 35 Lê Văn Lương, phường Nhân Chính, Thanh Xuan, Ha Noi',
 '351/45 Le Van Sy, Ward 13, District 3, Ho Chi Minh',
 'Charmington La Pointe Officetel Apartments, 181 Cao Thang St, District 10, Ho Chi Minh',
 'Tầng 14, Tòa Handico Phạm Hùng,, Nam Tu Liem, Ha Noi',
 'Lầu 2, Khu C, Tòa nhà Waseco, 10 Phổ Quang, Phường Tân Sơn Hòa, Thành phố Hồ Chí Minh, Việt Nam, Tan Binh, Ho Chi Minh',
 'Tầng 6A, Tháp C, tòa nhà Center Point, số 219 Trung Kính, Yên Hòa, Cau Giay, Ha Noi',
 'Tầng 19 tòa nhà HH2 Bắc Hà, 15 Tố Hữu, Nam Tu Liem, Ha Noi',
 'Tầng 8, Tòa nhà Hapro Building, 11B Cát Linh, Dong Da, Ha Noi',
 '03 Tran Nhan Ton, Ward 9, District 5, Ho Chi Minh',
 '89 Lang Ha, Dong Da, Ha Noi',
 'Tầng 12A, Tháp Tây, tòa nhà LOTTE Center Hà Nội, 54 Liễu Giai, Ba Dinh, Ha Noi',
 'Số 6 Quang Trung, phường Trần Hưng Đạo, Hoan Kiem, Ha Noi',
 '6th Floor, Lumiere Riverside - West Tower, 275 Vo Nguyen Giap, An Phu Ward, District 2, Thu Duc City, Ho Chi Minh City, Thu Duc City, Ho Chi Minh',
 '2nd Floor, Detech II Tower, 107 Nguyen Phong Sac Str, Cau Giay, Ha Noi',
 'C5 Building Tower, D’Capitale Tower, 119 Tran Duy Hung, Cau Giay, Ha Noi',
 'The Sentry P Building - 7th Floor, 16 Nguyen Dang Giai, Thao Dien Ward, Thu Duc City, Ho Chi Minh City, Vietnam, Thu Duc City, Ho Chi Minh',
 'Tòa nhà TechnoPark, Oceanpark, Đa Tốn, Gia Lam, Ha Noi',
 '91/2 đường Trần Thị Cờ, Khu phố 14, Phường Thới An, TP Hồ Chí Minh, Việt Nam, District 11, Ho Chi Minh',
 '71 Ngô Sĩ Liên, Dong Da, Ha Noi',
 'Toà nhà Epic, ngõ 19 Duy Tân, Cau Giay, Ha Noi',
 '2nd floor, 58 To Huu street, Nam Tu Liem, Ha Noi',
 'Tòa nhà TechnoPark, khu đô thị Vinhomes OceanPark 1, Gia Lam, Ha Noi',
 '91 Tan Cang Street, Ward 25, Binh Thanh, Ho Chi Minh',
 '138/ 38 Trương Công Định, phường Tân Bình, District 1, Ho Chi Minh',
 'Z06 Đường số 13, Phường Tân Thuận Đông, Ho Chi Minh',
 'Trụ sở GHTK Building, số 8 Phạm Hùng, Phường Từ Liêm, Ha Noi',
 'Phường Đức Nhuận, Phu Nhuan, Ho Chi Minh',
 'Remote, Ha Noi',
 'Vinamilk Tower, 10 Tan Trao St., Tan Phu Ward., , District 7, Ho Chi Minh',
 'Tầng 12, Citilight Tower, Số 45 Võ Thị Sáu, Phường Đa Kao, District 1, Ho Chi Minh',
 'CMC Creative Space, District 7, Ho Chi Minh',
 '22 Ngô Quyền, Hoan Kiem, Ha Noi',
 '173 Tran Nao, An Khanh, Thu Duc City, Ho Chi Minh',
 'Floor 12, Halo Signature Building, 257 Điện Biên Phủ, Xuan Hoa Ward, Ho Chi Minh City, District 3, Ho Chi Minh',
 '10 Floor, Dai Minh Tower, 77 Hoang Van Thai Street, Tan Phu Ward, District 7, Ho Chi Minh',
 '8th Floor, Capital Building, 58 Kim Ma Street, Ba Dinh, Ha Noi',
 '29A Nguyen Dinh Chieu, District 1, Ho Chi Minh',
 'Tower 2 (T26) Times City, 458 Minh Khai, Hai Ba Trung, Ha Noi',
 '63 Phạm Ngọc Thạch, Phường 6, Quận 3, Hồ Chí Minh, Việt Nam, District 3, Ho Chi Minh',
 'Số 669 Điện Biên Phủ, Phường Thạnh Mỹ Tây, Binh Thanh, Ho Chi Minh',
 'Tầng 15, tòa nhà MB – 21 Cát Linh, phường Cát Linh, Dong Da, Ha Noi',
 '12A Núi Thành, Tan Binh, Ho Chi Minh',
 '34 Đường Số 11, Phường An Khánh, Thu Duc City, Ho Chi Minh',
 'ROX Tower, 54A Nguyen Chi Thanh, phuong Lang Thuong, Dong Da, Ha Noi',
 '222 Pasteur, Phường Xuân Hòa, District 3, Ho Chi Minh',
 '32 Pham Ngoc Thach, Ward Vo Thi Sau, District 3, Ho Chi Minh',
 '629 Nguyễn Kiệm, Phường 9, Quận Phú Nhuận, TP.HCM, Phu Nhuan, Ho Chi Minh',
 'Tầng 1, số 127 Hồng Hà, Phường Đức Nhuận, TP. Hồ Chí Minh, Việt Nam., Phu Nhuan, Ho Chi Minh',
 'Tòa nhà CMC , số 11 Duy Tân, Dịch Vọng Hậu, Cầu Giấy, Hà Nội, Ha Noi',
 'Thảo Điền, Thu Duc City, Ho Chi Minh',
 '124 Dien Bien Phu, Tan Dinh Ward, District 1, Ho Chi Minh',
 '25 Nguyễn Thị Minh Khai, District 1, Ho Chi Minh',
 'Lotte Tower, 54 Lieu Giai, Ba Dinh, Ha Noi',
 '1 Thai Ha, Dong Da, Ha Noi',
 'Tầng 2, Tòa nhà GIC, 10A Nguyễn Thị Minh Khai, District 1, Ho Chi Minh',
 'Sun Ancora, 03 Lương Yên, Hai Ba Trung, Ha Noi',
 'VNG Campus, Tân Thuận Đông, District 7, Ho Chi Minh',
 'City, Ho Chi Minh',
 'The Hallmark Building, 15 Tran Bach Dang Str, Thu Thiem Ward, Thu Duc City, Ho Chi Minh',
 'Tầng 15, tòa Keangnam Landmark 72, Mễ Trì, Nam Tu Liem, Ha Noi',
 'Tầng 04, Tòa nhà số 5 Điện Biên Phủ, Phường Ba Đình, Ba Dinh, Ha Noi',
 '6th Floor, Menas Mall Saigon Airport, 60A Truong Son, Tan Son Hoa Ward, Tan Binh, Ho Chi Minh',
 'Floor 16th, Unit B1-B3-B4, International Plaza Tower, No. 343, Pham Ngu Lao Street, District 1, Ho Chi Minh',
 'Tầng 19, tòa nhà Peakview Tower, 36 Hoàng Cầu, Đống Đa, Hà Nội, Dong Da, Ha Noi',
 'TGI Building, 208 Nguyen Trai, District 1, Ho Chi Minh',
 '149-151 Nguyen Van Troi, Ward 11, Phu Nhuan, Ho Chi Minh',
 'Tầng 11, số 41 Hai Bà Trưng, Phường Cửa Nam, Ha Noi',
 'L07.01, Tầng 07, Tháp A, Khu thương mại dịch vụ kết hợp nhà ở cao tầng tại lô đất 1-13, thuộc khu chức năng số 1 – Số 15, đường Trần Bạch Đằng, Phường Thủ Thiêm, Thu Duc City, Ho Chi Minh',
 'Lim 3 Tower, 29A Nguyễn Đình Chiểu, Phường Sài Gòn, Ho Chi Minh',
 'Tầng 3, số 6 ngõ 82 Duy Tân, phường Dịch Vọng Hậu, Cau Giay, Ha Noi',
 'Flemington Tower, 182 Le Dai Hanh Street, District 11, Ho Chi Minh',
 '6th Floor, Phu My Hung Tower, 08 Hoang Van Thai Str, Tan Mỹ Ward, District 7, Ho Chi Minh',
 'Tầng 4, Tòa nhà Văn Phòng HH1 Meco Complex, ngõ 102 Trường Chinh, Phương Mai, Đống Đa, Ha Noi',
 'Nhà N4-Khuôn viên Trường Mầm non Lý Thái Tổ, số 2 Nguyễn Thị Thập, phường Yên Hoà, Ha Noi',
 '107 Nguyen Phong Sac, Dich Vong Hau, Cau Giay, Ha Noi',
 'Tòa nhà E.Town Central, Số 11 Đoàn Văn Bơ, Phường Xóm Chiếu, TP.HCM, Ho Chi Minh',
 'Tầng 12B tòa nhà Machinco, 444 Hoàng Hoa Thám, Thụy Khuê, Tay Ho, Ha Noi',
 'Helios Bldg + QTSC9, Quang Trung Software City, Tan Chanh Hiep Ward, District 12, Ho Chi Minh',
 '77 Tran Nhan Ton, District 5, Ho Chi Minh',
 'Tầng 5A, Nhà 25T2 - Lô Đất N05 - Khu Đô Thị Đông Nam, Đường Trần Duy Hưng, Phường Yên Hòa, Ba Dinh, Ha Noi',
 '131 Xo Viet Nghe Tinh 17 Ward, Binh Thanh, Ho Chi Minh',
 'Tòa nhà ETOWN 6 - 364 Cộng Hòa, Phường 13, Tan Binh, Ho Chi Minh',
 'Số 2, ngõ 95, phố Chùa Bộc, Dong Da, Ha Noi',
 'The Hallmark, 15 Tran Bach Dang, Thu Thiem Ward, Thu Duc City, Ho Chi Minh',
 '24th floor, Discovery Complex Office Tower, No. 302 Cau Giay Street, Cau Giay, Ha Noi',
 'Tòa nhà The Summit Building, 350 Nguyễn Văn Linh, Phường Thanh Khê, Thành phố Đà Nẵng, Việt Nam, Thanh Khe, Da Nang',
 '246 Cong Quynh, Pham Ngu Lao Ward, District 1, Ho Chi Minh',
 'Tầng 30 - Tòa tháp C5 D’Capital, 119 Trần Duy Hưng, Phường Yên Hoà, Thành phố Hà Nội, Việt Nam, Ba Dinh, Ha Noi',
 '6Fl, DC Tower, 111D Ly Chinh Thang Street, Xuan Hoa Ward, District 3, Ho Chi Minh',
 '17 Nguyen Duy Hieu, Thu Duc City, Ho Chi Minh',
 '24 Huỳnh Khương Ninh, Phường Đa Kao, Quận 1, District 1, Ho Chi Minh',
 'G Floor, City House Building, Nguyen Dinh Chieu Street, Ban Co Ward, District 3, Ho Chi Minh',
 'Aloha Building, 68 Hong Ha, Ward 2, Tan Binh, Ho Chi Minh',
 'Etown 1 Building, Unit 9.2, 364 Cong Hoa Street, Ward 13, Tan Binh District, Tan Binh, Ho Chi Minh',
 '341-343, Dien Bien Phu - Hd Bank Building , Binh Thanh, Ho Chi Minh',
 '68 Hong Ha, Tan Binh, Ho Chi Minh',
 '81 Điện Biên Phủ, Phường Tân Định, District 1, Ho Chi Minh',
 'Số 1 Phùng Chí Kiên, Cầu Giấy, Ha Noi',
 '366 Nguyễn Trãi, District 5, Ho Chi Minh',
 'Số 5, đường số 5, KCN Sóng Thần 1, Di An, Binh Duong',
 'Tầng 11, Cao ốc Saigon Trade Center, 37 Tôn Đức Thắng, Phường Sài Gòn, Thành phố Hồ Chí Minh, Việt Nam, District 1, Ho Chi Minh',
 'Tầng 4, 41 Nguyễn Phước Lan, Hòa Xuân, Da Nang',
 'Keangnam Landmark, Nam Tu Liem, Ha Noi',
 'Level 6-7, East Tower,  Lumiere Riverside, 277 Vo Nguyen Giap,  An Khanh Ward, Thu Duc City, Ho Chi Minh',
 'Phòng 602, 1003, 1004, 1401 Tháp Royal Tower B, Tòa Nhà Royal Centre, 235 Nguyễn Văn Cừ, Phường Nguyễn Cư Trinh, Q.1, TP.HCM, Việt Nam, District 1, Ho Chi Minh',
 '45-47 Trần Xuân Soạn, Hai Ba Trung, Ha Noi',
 'Shophouse Vinhomes Gardenia, Nam Tu Liem, Ha Noi',
 'Apartment B1, D’ Verano Residential, Thu Thiem new urban area, An Khanh Ward, Thu Duc City, Ho Chi Minh',
 'Tầng 9, Tòa nhà TNR, 180-192 Nguyễn Công Trứ, Phường Nguyễn Thái Bình, District 1, Ho Chi Minh',
 'F-Town 3, Lô E3 Võ Chí Công, Khu CNC, Phường Tăng Nhơn Phú,, Thu Duc City, Ho Chi Minh',
 'Hong Ha, Phu Nhuan, Ho Chi Minh',
 'Tòa Detech Building, Số 8 Tôn Thất Thuyết, Cau Giay, Ha Noi',
 'Tầng 16 - Tháp A, Tòa nhà văn phòng HUD Tower, số 37 Lê Văn Lương, , Thanh Xuan, Ha Noi',
 '9th Floor, Etown 6 Building, 364 Cong Hoa Street, Ward 13, Tan Binh District, Ho Chi Minh City, Tan Binh, Ho Chi Minh',
 '1/12 Hoàng Việt, Phường 4, Tân Bình, Hồ Chí Minh, Vietnam, Tan Binh, Ho Chi Minh',
 '2nd Floor, Ework Building 103A-105-107 Nguyen Thong street, Nhieu Loc Ward , Ho Chi Minh',
 '307/20-21 Nguyen Van Troi, Tan Son Hoa Ward, Ho Chi Minh',
 'Toà nhà Hana Building, 455 Hoàng Sa , District 3, Ho Chi Minh',
 'Sarina, Sala, Thủ Thiêm, Thu Duc City, Ho Chi Minh',
 '9 Dinh Tien Hoang, Tan Dinh Ward, District 1, Ho Chi Minh',
 'Savills Vietnam – 18th floor, Doji Tower, 81 - 85 Ham Nghi Street, Nguyen Thai Binh Ward, District 1, Ho Chi Minh',
 'Hồ Chí Minh, District 1, Ho Chi Minh',
 '106 Nguyen Van Troi Street, Phu Nhuan, Ho Chi Minh',
 'Tầng 5, Tòa Toyota số 15 Phạm Hùng, Nam Từ Liêm, Ha Noi',
 'Mạc Đĩnh Chi, District 1, Ho Chi Minh',
 '15A Nguyễn Trung Trực, ward 5, Binh Thanh, Ho Chi Minh',
 '30 Nguyễn Thị Diệu , District 3, Ho Chi Minh',
 '248A No Trang Long, Binh Thanh, Ho Chi Minh',
 'Tầng 3 , w2 , tòa nhà VINHOMES WestPoint Phạm Hùng, Nam Tu Liem, Ha Noi',
 'Tầng 8, tòa nhà Kim Ánh, 78 Duy Tân, Cau Giay, Ha Noi',
 'Cobi Tower II, No. 2-4, Street No. 8, Tan Phu Ward, District 7, Ho Chi Minh',
 'Lim Tower 3, 29A Nguyen Dinh Chieu Street, Tan Dinh Ward , District 1, Ho Chi Minh',
 '17 Đường số 2, Cư xá Đô Thành, District 3, Ho Chi Minh',
 '7th floor, Loyal building, 151 Võ Thị Sáu, phường Võ Thị Sáu, quận 3, TPHCM, District 3, Ho Chi Minh',
 '54 - 56 Lê Quốc Hưng, Phường 13, District 4, Ho Chi Minh',
 'Tầng 20A, Vincom Center Đồng Khởi, 72 Lê Thánh Tôn, phường Bến Nghé, District 1, Ho Chi Minh',
 '3rd Floor, Dong Nhan Building, 90 Nguyen Dinh Chieu, Tan Dinh Ward, Ho Chi Minh',
 'Công ty Cổ phần Ứng dụng công nghệ Logistics (Logistics Technology Application Joint Stock Company) (LTA), 2A Đường Số 5, An Phú, Thu Duc City, Ho Chi Minh',
 'No. 53-55-57, Pho Duc Chinh street, Nguyen Thai Binh ward, District 1, Ho Chi Minh',
 'Tầng 4, tòa nhà Lucky, số 81 Trần Thái Tông, phường Cầu Giấy, Ha Noi',
 'Tòa Nhà Flemington, 182 Lê Đại Hành, Phường Phú Thọ, Ho Chi Minh',
 '9th Floor, 174 Thai Ha Street, Trung Liet Ward, Dong Da, Ha Noi',
 'Vincom Center Đồng Khởi, 45A Lý Tự Trọng, p. Bến Nghé,, District 1, Ho Chi Minh',
 'XL Building, 167 Tran Nao Street, An Khanh Ward, (former District 2) , Thu Duc City, Ho Chi Minh',
 'UDIC Complex, N04 Hoàng Đạo Thúy, Cau Giay, Ha Noi',
 '52A Trần Bình Trọng, Phường Bình Lợi Trung, Ho Chi Minh',
 'Viettel Building, 285 Cach Mang Thang Tam Street, Hoa Hung Ward, HCMC., District 10, Ho Chi Minh',
 '21 Phùng Khắc Khoan, Phường Sài Gòn, District 1, Ho Chi Minh',
 'Lancaster Luminaire Hà Nội, 1154 Đường Láng, Phường Láng, Ha Noi',
 "Toà nhà L'Mak, Số 68 Đường Phan Đăng Lưu, Phường 5, Phu Nhuan, Ho Chi Minh",
 '62 Tran Quang Khai, Tan Dinh Ward, District 1, Ho Chi Minh',
 'Tầng 8, Tòa nhà VP Sông Hồng , 165 Thái Hà , Đống Đa , Hà Nội, Dong Da, Ha Noi',
 'F-Central, 16A Le Hong Phong, ward 12, District 10, Ho Chi Minh',
 'Remotely, Floor 13, MB Sunny Tower, 259 Tran Hung Dao, Co Giang ward, District 1, Ho Chi Minh',
 'Mitalab Tower, 379 - 383B - 385 Cong Hoa Street, Tan Binh, Ho Chi Minh',
 '48Bis Trần Đình Xu, cô giang, District 1, Ho Chi Minh',
 '., Other, Ho Chi Minh',
 'Phòng 6.5, Etown 2, 364 Cộng Hòa, Phường Tân Bình, Tan Binh, Ho Chi Minh',
 'Tầng 2, tòa nhà Itaxa, 126 Nguyễn Thị Minh Khai, Phường Xuân Hòa, District 1, Ho Chi Minh',
 'Viettel Tower, 285 CMT8, District 10, Ho Chi Minh',
 '67 Đinh Bộ Lĩnh, Binh Thanh, Ho Chi Minh',
 '2ⁿᵈ Floor, SECC, 799 Nguyen Van Linh Street, Tan My Ward, District 7, Ho Chi Minh',
 'Ho Chi Minh City (remote flexibility)',
 '140B Nguyen Van Troi street, Phu Nhuan, Ho Chi Minh',
 'Tòa Hàn Việt, 203 Minh Khai, Phường Minh Khai, Hai Ba Trung, Ha Noi',
 'Anna building, Quang Trung software city, District 12, Ho Chi Minh',
 'Tầng Lửng, Tòa nhà Saigon View, 117 Nguyễn Cửu Vân, Phường Gia Định, Ho Chi Minh',
 'Tòa nhà 175 Giảng Võ, Dong Da, Ha Noi',
 'Tầng 3, tòa nhà Mipec Tower, 229 Tây Sơn, Khương Thượng, Đống Đa, Ha Noi',
 '1 Luong Yen, Hai Ba Trung, Ha Noi',
 '1295 1295B, Nguyễn Thị Định, Phường Cát Lái, District 2, Ho Chi Minh',
 'Tòa nhà A5, Lô số A5, khu E-Office, đường Sáng Tạo, KCX Tân Thuận, Phường Tân Thuận, District 7, Ho Chi Minh',
 'Số 2, Ngõ 15, Đường Duy Tân, Phường Dịch Vọng Hậu, Quận Cầu Giấy, Hà Nội, Cau Giay, Ha Noi',
 'Tầng 31, tòa Keangnam Hanoi Landmark 72, Lô E6,  Đường Phạm Hùng, Phường Mễ Trì, Quận Nam Từ Liêm, Hà Nội, Nam Tu Liem, Ha Noi',
 'Bach building, 111 Ly Chinh Thang, Vo Thi Sau ward, District 3, Ho Chi Minh',
 'Tầng 20, Toà Nhà 319 BQP, 63 Lê Văn Lương, Cau Giay, Ha Noi',
 '90 Nguyễn Tuân, Thanh Xuan, Ha Noi',
 'Tầng 21, Phú Mỹ Hưng Tower, số 08 Hoàng Văn Thái, Phường Tân Phú, District 7, Ho Chi Minh',
 'CII Building, 152 Dien Bien Phu, Thanh My Tay Ward , Binh Thanh, Ho Chi Minh',
 '14F, 89 Phan Dinh Phung, Cau Kieu Ward, Ho Chi Minh City, Phu Nhuan, Ho Chi Minh',
 'BIDV Tower, 194 Tran Quang Khai, Hoan Kiem, Ha Noi',
 'D003 chung cư Sadora , số 2, đường số 13, Phường Thủ Thiêm, Thu Duc City, Ho Chi Minh',
 'No. 16 BT4-3, Trung Van Residential Area, Dai Mo Ward, Hanoi, Vietnam, Nam Tu Liem, Ha Noi',
 'Tòa nhà Waseco Building, 10 Phổ Quang, Phường 2, Ho Chi Minh',
 'Khu công nghiệp Thạch Thất- Quốc Oai, xã Tây Phương, Ha Noi',
 '23 đường số 53, Phường Bình Trưng, Thu Duc City, Ho Chi Minh',
 '19 Tan Canh, Tan Binh, Ho Chi Minh',
 'Tòa Handico Phạm Hùng, Mễ Trì, Nam Tu Liem, Ha Noi',
 'Tầng 17 đến tầng 21, Tòa văn phòng, Lotte Mall Hà Nội, Số 272 Võ Chí Công, Phường Phú Thượng, Quận Tây Hồ, Thành phố Hà Nội, Tay Ho, Ha Noi',
 '106 Hoàng Quốc Việt, Cau Giay, Ha Noi',
 'Tòa nhà Saigon Trade Center (37 Tôn Đức Thắng, P. Sài Gòn), District 1, Ho Chi Minh',
 '3rd Floor, Rivera Park Building, 7/28 Thanh Thai, Ho Chi Minh',
 'Tầng 5A, Nhà 25T2 - Lô Đất N05 - Khu Đô Thị Đông Nam, Đường Trần Duy Hưng, Phường Yên Hòa, Ha Noi',
 'Floor 8, A3 Tower, Ecolife Capital, No.58 To Huu, Me Tri Ward, Ha Noi',
 'Tầng 2, Số 56 Sunrise G, The Manor Central Park, Nguyễn Xiển, Đại Kim, Hoàng Mai, Hà Nội, Ha Noi',
 'IM Tower 3 - 21st Floor, 29A Nguyen Dinh Chieu, Sai Gon Ward, Ho Chi Minh',
 '46 Bach Dang Street, Ward 2, Ho Chi Minh',
 '5A Tran Phu, Ho Chi Minh',
 'Tòa nhà Waseco số 10 Phổ Quang, Tan Son Hoa, Ho Chi Minh',
 'No. 53-55-57, Pho Duc Chinh street, Nguyen Thai Binh ward, Ho Chi Minh',
 'The Hallmark, 15 Tran Bach Dang, Thu Thiem Ward, Ho Chi Minh',
 '235 Nguyễn Văn Cừ, Ho Chi Minh',
 '43 Lê Văn Lương, Nhân Chính, Ha Noi',
 'ROX Tower, 54A Nguyen Chi Thanh, phuong Lang Thuong, Ha Noi',
 '324 Le Van Sy, Ward 2, Ho Chi Minh',
 'Tầng 21, Phú Mỹ Hưng Tower, số 08 Hoàng Văn Thái, Phường Tân Phú, Tan My, Ho Chi Minh',
 'Tòa HUD 37 Lê Văn Lương, Ha Noi',
 'Tầng 19 tòa nhà HH2 Bắc Hà, 15 Tố Hữu, Ha Noi',
 '9th Floor, Dreamplex Building,195 Đien Bien Phu, Ward 15, Ho Chi Minh',
 '138/ 38 Trương Công Định, phường Tân Bình, Ho Chi Minh',
 '6th Floor, Lumiere Riverside - West Tower, 275 Vo Nguyen Giap, An Phu Ward, District 2, Thu Duc City, Ho Chi Minh City, Ho Chi Minh',
 '63 Phạm Ngọc Thạch, Phường 6, Quận 3, Hồ Chí Minh, Việt Nam, Ho Chi Minh',
 'Tower 2 (T26) Times City, 458 Minh Khai, Ha Noi',
 '10 Floor, Dai Minh Tower, 77 Hoang Van Thai Street, Tan Phu Ward, Ho Chi Minh',
 '5th Floor, 19 Duy Tan, Zodiac Building, Ha Noi',
 'Ho Chi Minh, Ho Chi Minh',
 'REE Tower, 9 Doan Van Bo, Ward 12, Ho Chi Minh',
 'Nam Ky Khoi Nghia, Ho Chi Minh',
 'Z06 Street No. 13, Tan Thuan Dong Ward, Ho Chi Minh',
 'QTSC Building 1, Quang Trung Software City, Trung My Tay, Ho Chi Minh',
 '95-97 Nguyễn Cơ Thạch, Phường An Lợi Đông, Thành phố Thủ Đức, TP Hồ Chí Minh, Ho Chi Minh',
 '1/12 Hoàng Việt, Phường 4, Tân Bình, Hồ Chí Minh, Vietnam, Ho Chi Minh',
 '508 Đ. Trường Chinh, Khương Thượng, Ha Noi',
 'The Grace Tower, Ho Chi Minh',
 'tầng 26, tòa nhà The West, 265 Cầu Giấy, Ha Noi',
 'Sailing Tower, 111A Pasteur, Ward Sai Gon, Ho Chi Minh',

In [11]:
# Cột salary có bao nhiêu giá trị duy nhất
df['salary'].unique().tolist()

['20-25tr gross',
 "You'll love it",
 'Up to 2800 usd',
 'Up-to 34,000 usd/year',
 '1,500 - 3,900 USD',
 '1,000 - 3,500 USD',
 '800 - 1,000 USD',
 '1,000 - 3,000 USD',
 '500 - 900 USD',
 '600 - 1,500 USD',
 '1,000 - 1,500 USD',
 '500 - 1,200 USD',
 '500 - 1,000 USD',
 '1,000 - 1,700 USD',
 '1,000 - 2,000 USD',
 '1,500 - 2,000 USD',
 '700 - 2,500 USD',
 'Up to 40m',
 '1,000 - 1,300 USD',
 '1,000 - 2,200 USD',
 '700 - 1,200 USD',
 'Up to $2000',
 'Very attractive!!!',
 '2,800 - 4,000 USD',
 'Negotiable - up to 150m',
 '2,500 - 4,500 USD',
 '2,000 - 2,800 USD',
 '900 - 1,200 USD',
 '1,200 - 2,500 USD',
 'Upto 35.000.000',
 '1,900 - 2,600 USD',
 '700 - 2,000 USD',
 '2,000 - 3,000 USD',
 '2,000 - 2,500 USD',
 'Up to $1000',
 'Negotiation',
 nan,
 'Upto 40m',
 '500 - 600 USD',
 'Very competitive',
 'Up to 1000$',
 '2,500 - 3,500 USD',
 '18,000,000-30,000,000',
 '1,500 - 2,800 USD',
 'Up to 60m',
 '30,000,000 - 50,000,000đ',
 'Up to 1400$',
 'Negotiable + full bhxh',
 '800 - 2,000 USD',
 '700 - 1,000 USD',
 '900 - 2,000 USD',
 '500 - 700 USD',
 'Negotiable',
 '1,500 - 2,500 USD',
 '1,000 - 2,500 USD',
 'Thỏa thuận từ 20 triệu',
 '1,200 - 2,200 USD',
 'Up to 45m (gross)',
 '1,500 - 3,000 USD',
 'Open to negotiation',
 '1,500 - 2,300 USD',
 '750 - 1,100 USD',
 'Upto 40.000.000 vnd',
 '15 - 50m',
 'Up to 40mil net',
 'Từ 25tr trở lên',
 'Competitive',
 '2,000 - 4,000 USD',
 '30.000.000 - 35.000.000',
 'Upto 50tr/tháng',
 '700 - 1,500 USD',
 'Attractive',
 '600 - 1,000 USD',
 "Let's discuss",
 '800 - 2,500 USD',
 '1,000 - 2,498 USD',
 '2,000 - 3,500 USD',
 '800 - 1,200 USD',
 '700 - 1,600 USD',
 '1,700 - 3,000 USD',
 'Highly competitive',
 '2,500 - 3,000 USD',
 '1,500 - 4,000 USD',
 'Upto 3500$',
 '1,300 - 2,000 USD',
 '1,000 - 2,300 USD',
 'You’ll love it',
 '1,000 - 1,600 USD',
 '1,000 - 1,800 USD',
 '1,600 - 2,500 USD',
 'Up to 70,000,000',
 '1,200 - 2,100 USD',
 '2,000 - 2,300 USD',
 '1,200 - 1,700 USD',
 '800 - 1,500 USD',
 'Thương lượng',
 '1,200 - 1,800 USD',
 '10-15 triệu/tháng',
 '600 - 2,600 USD',
 '7m-15m',
 '1,400 - 3,000 USD',
 '1,800 - 2,200 USD',
 '500 - 1,500 USD',
 '35tr-55tr',
 '500 - 1,100 USD']

In [12]:
# Cột category có bao nhiêu giá trị duy nhất
df['is_fresher'].unique().tolist()

['No', 'Yes']

In [6]:
# Cột job_type có bao nhiêu giá trị duy nhất
df['job_type'].unique().tolist()

['At office',
 'Hybrid',
 '10th Floor, VCN Tower, 2 To Huu Street (Onsite/Hybrid), Nha Trang, Khanh Hoa',
 'Remote',
 'Remote, Ha Noi',
 'Remotely, Floor 13, MB Sunny Tower, 259 Tran Hung Dao, Co Giang ward, District 1, Ho Chi Minh',
 'Ho Chi Minh City (remote flexibility)',
 'Location 2: Hybrid, Ho Chi Minh',
 'Fullly Remote, Sai Gon, Ho Chi Minh',
 '[Remote] , Ha Noi']

In [7]:
# Cột date_post có bao nhiêu giá trị duy nhất
df['date_post'].unique().tolist()

['2026-04-05',
 '2026-04-04',
 '2026-04-02',
 '2026-04-01',
 '2026-03-31',
 '2026-03-30',
 '2026-03-25',
 '2026-04-03',
 '2026-03-11',
 '2026-03-05',
 '2026-03-26',
 '2026-03-12',
 '2026-03-10',
 '2026-03-28',
 '2026-03-27',
 '2026-03-24',
 '2026-03-23',
 '2026-03-20',
 '2026-03-19',
 '2026-03-18',
 '2026-03-16',
 '2026-03-15',
 '2026-03-14',
 '2026-03-08',
 '2026-03-07',
 '2026-03-06',
 '2026-03-04',
 '2026-03-03',
 '2026-03-02',
 '2026-03-21',
 '2026-03-22',
 '2026-03-17',
 '2026-04-06',
 '2026-03-09',
 '2026-03-29',
 '2026-03-13',
 '2026-04-08',
 '2026-04-17',
 '2026-04-11',
 '2026-04-16',
 '2026-04-14',
 '2026-04-13',
 '2026-04-10',
 '2026-04-09',
 '2026-04-07',
 nan,
 '2026-04-15',
 '2026-04-12',
 '2026-04-19',
 '2026-04-18',
 '2026-04-23',
 '2026-04-22',
 '2026-04-21',
 '2026-04-24',
 '2026-04-25',
 '2026-04-27',
 '2026-04-26',
 '2026-04-28',
 '2026-05-01',
 '2026-04-30',
 '2026-04-29',
 '2026-05-04',
 '2026-05-03',
 '2026-05-08',
 '2026-05-06',
 '2026-05-07',
 '2026-05-05',
 '2026-05-12',
 '2026-05-09',
 '2026-05-11',
 '2026-05-16',
 '2026-05-15',
 '2026-05-14',
 '2026-05-13',
 '2026-05-10',
 '2026-05-17',
 '2026-05-18',
 '2026-05-21',
 '2026-05-19',
 '2026-05-20',
 '2026-05-22',
 '2026-05-23']

In [8]:
# Cột job_skills (kỹ năng công việc) có bao nhiêu giá trị duy nhất
df['job_skills'].unique().tolist()

['Data Analysis, Databricks, SQL, Data modeling, Power BI',
 'Data Analysis, Data Warehousing, ETL, Power BI, Tableau, SQL',
 'Data Analysis, Power BI, SQL, Agile, Python',
 'Data Analysis, Looker, Tableau, Power BI, English',
 'Data Analysis, Microsoft Power Apps, SQL',
 'Python, SQL',
 'Data Analysis, Power BI, Microsoft SQL Server, Oracle, SQL',
 'Data Analysis, Business Intelligence, JSON, API, SQL, Python',
 'Business Analysis, Data Analysis',
 'Data Analysis, SQL, AI, Looker, Power BI',
 'SQL, English',
 'Data Analysis, Business Intelligence, Power BI, Data modeling, Data Warehousing, Database',
 'Data Analysis, PostgreSql, Database, SQL, Business Intelligence',
 'Data Analysis, English, Python, Microsoft SQL Server, SQL, Power BI',
 'Business Analysis, English',
 'SQL, PostgreSql, Data modeling, Data Analysis, Database, Data Warehousing',
 'Data Analysis, PL/SQL, Oracle, Data modeling, ETL, Business Intelligence',
 'Business Analysis, Product Management, Games, Product Owner, Jira, Data-driven',
 'Business Intelligence, Data modeling, Data Analysis, Power BI, Business Analysis',
 'Business Analysis, UI-UX, Scrum, Agile',
 'Business Analysis, Figma, SQL, API',
 'Business Analysis, ERP, English, DevOps, Azure, Microsoft Dynamics 365',
 'Business Analysis, English, Scrum, Stakeholder management, Agile, Product Owner',
 'Business Analysis, API, Design Systems, Data modeling, AI, English',
 'Business Analysis, ERP, MySQL, SQL, English',
 'Business Analysis, SAP, Project Management, Product Owner',
 'Business Analysis, English, SQL',
 'Business Analysis, BRD, Stakeholder management, Data Analysis, Scrum, AI',
 'Business Analysis, DevOps, System Admin, Java, SQL',
 'Business Analysis, English, Agile, Jira',
 'Business Analysis, Power BI, PowerShell, ServiceNow, Python',
 'Business Analysis, SQL, Database',
 'Power BI, Looker, Python, MySQL, Tableau, SQL',
 'Data Engineer, Power BI, Tableau, Business Intelligence, Cloud, Oracle',
 'Business Analysis, Database, System Admin, Stakeholder management, Product Management',
 'Business Analysis, Jira, Data Quality Tools, CRM, ERP',
 'Business Analysis, Figma, Mockups, UML, Scrum, BPMN',
 'Business Analysis, OCR, LLM, Database, AI',
 'Business Analysis, System Admin, ERP, API, Database, CRM',
 'Business Analysis, ERP, SAP, English',
 'Business Analysis, IT Communication/Translation, BPMN, Agile, Azure, Jira',
 'Business Analysis, SRS, BRD, English, Scrum, Agile',
 'Business Analysis, Team Management, English, SQL, Agile',
 'Business Analysis, Project Management, Product Owner, English, AI, Technical Writing',
 'Business Analysis, Agile, BPMN, UML, English',
 'Business Analysis, API, Java, Microservices, Cloud, .NET',
 'Business Analysis, Stakeholder management, Figma, BRD, Agile, UML',
 'Business Analysis, NoSQL, SQL, Scrum, Agile',
 'Business Analysis, CRM, UML, Jira, Figma, English',
 'Business Analysis, Scrum, Agile, SRS',
 'Business Analysis, Team Management, Agile, Design Systems, SRS, UML',
 'Business Analysis, Project Management, SQL, Jira, Scrum, Agile',
 'Business Analysis, Data Analysis, Jira',
 'Business Analysis, User story, SQL, Jira, UML, BPMN',
 'Business Analysis, Scrum, Agile, English',
 'Business Analysis, SRS, AI, BRD, English',
 'Business Analysis, Agile, Data Analysis, Team Management, Leadership, English',
 'Business Analysis, Prototyping, Stakeholder management, UML, Scrum, Agile',
 'Business Analysis, Project Management, Product Management, Software Architecture, English, Agile',
 'Business Analysis, Prototyping, Mockups, SQL',
 'Business Analysis, CRM, ERP, UML, BPMN',
 'Business Analysis, Japanese IT Communication, Bridge Engineer, IT Communication/Translation',
 'UML, BPMN, Wireframing',
 'Business Analysis, PQA, Stakeholder management, Product Metrics, Product Management, Product Owner',
 'Business Analysis, Product Owner, Agile, English',
 'Business Analysis, Project Management, Agile',
 'Business Analysis, Data Analysis, SQL, English, Tester, Project Management',
 'Business Analysis, UML, Figma, English',
 'Business Analysis, Oracle, ERP, SQL',
 'Project Management, Product Owner, Business Analysis, Scrum, Leadership, English',
 'Team Management, Business Analysis, JQuery, SQL, Design, Project Management',
 'Project Management, BRD, Leadership, CRM, Business Analysis',
 'Business Analysis, Agile, AI, BRD',
 'Data Engineer, Business Intelligence, Data Warehousing, PostgreSql, SQL, Oracle',
 'Machine Learning, Kubernetes, Spark, Linux, Data Engineer',
 'Data Science, Keras, Deep Learning, Machine Learning, Matlab',
 'Oracle, AWS, Redis, MongoDB, PostgreSql, Cloud',
 'Big Data, AI, Data Science',
 'Data-driven, Team Management, Data Quality Tools, English, Data Privacy / Compliance',
 'Big Data, Power BI, TensorFlow, Python, SQL, Solution Architecture',
 'Data Privacy / Compliance, Cloud Security, Data Quality Tools, Data Science',
 'Data Science, Machine Learning, AI, IT Governance',
 'Data Engineer, SQL, Python, AI, ETL, English',
 'Data Engineer, CI/CD, Scala, Spark, Python, Cloud',
 'Data Engineer, ETL, Big Data, SQL, Databricks, Python',
 'Data Science, AWS, Pandas, PyTorch, Python, Generative AI',
 'Python, ETL, AWS',
 'AI, Data modeling, Data Warehousing, AWS, Python',
 'ETL, ReactJS, Data modeling, Data Warehousing, C#, Python',
 'Data Science, Data Analysis, XGBoost, scikit-learn, MLOps, Python',
 'Data Engineer, Database, Python, ETL, ELT, SQL',
 'Python, Scala, Data Warehousing, NoSQL, Git, SQL',
 'Database, AI, Linux, DevOps',
 'Oracle, Redis, MongoDB, PostgreSql, Azure, Cloud',
 'Software Architecture, Design, Team Management, JavaScript, Agile, Python',
 'Data Science, Pandas, scikit-learn, Deep Learning, Machine Learning, Python',
 'Python, AI, Cloud, Database, AWS, SQL',
 'Data Science, Pandas, Metabase, Machine Learning, SQL, Python',
 'Data Engineer, AI, PostgreSql, SQL, Python',
 'Statistical Analysis, Python',
 'Data Engineer, Hadoop, Big Data, Scala, Python, Java',
 'Apache Spark, SQL, Elasticsearch, Cassandra, Apache Airflow',
 'Data Engineer, ELT, Business Intelligence, AWS, SQL, Python',
 'Data Engineer, Terraform, Kafka, AWS, Data Warehousing, ETL',
 'Data Engineer, ETL, AWS, SQL, Python, English',
 'Python, AWS, Scala, Golang, Apache Spark',
 'Python, Data Quality Tools, Data Lineage, Database, PL/SQL, SQL',
 'Python, MongoDB, PostgreSql, AI, SQL',
 'Data Engineer, Data-driven, Databricks, Database',
 'Data Engineer, Spark, Java, Data Warehousing, Big Data, Database',
 'Microsoft SQL Server, Cloud-native Architecture, AWS Glue, Python, ETL, SQL',
 'Data Engineer, Databricks, Snowflake, Python, SQL, Power BI',
 'Data Engineer, Cloud, Oracle, Database, Python, SQL',
 'Python, Kubernetes, Docker, CI/CD, Microservices, AWS',
 'Data Engineer, ETL, Database, SQL, Data Warehousing, Data modeling',
 'Data Engineer, Python',
 'Business Analysis, Scrum, Agile, ERP, Product Management, Product Owner',
 'Governance, Risk & Compliance, Security, Risk Management, IT Audit, IT Governance',
 'AWS CloudFormation, Agile',
 'SQL, Power BI, Data Privacy / Compliance, Oracle, Tableau',
 'IT Support, Cybersecurity, Security',
 'PL/SQL, SQL, Business Intelligence, Business Analysis, Scrum, Agile',
 'Project Management, Business Intelligence, CRM, ERP',
 'Java, Security, Business Intelligence, Kubernetes, AWS, Microservices',
 'Big Data, English, Google Cloud, Python, AI, Data-driven',
 'Python, Data Science, Azure, Machine Learning, LLM',
 'Data Engineer, English, Data Warehousing, AWS, SQL, Python',
 'Data Engineer, English, AI, Azure, SQL, Python',
 'Solution Architecture, Data Engineer, Kubernetes, MLOps, Cloud, Kafka',
 'Automation Test, Playwright, Jmeter, Penetration Testing, SAP, QA QC',
 'AI, Data Engineer, MLOps, Machine Learning, ELT, Python',
 'IT Support, Security, Cybersecurity',
 'Database, Data Engineer, MongoDB, English, SQL, API',
 'Fullstack, Data Engineer, ReactJS, Java, C#, NodeJS',
 'Python, HTML, ETL, PostgreSql, FastAPI, Django',
 'GCP, Japanese, Terraform, Cloud',
 'Cloud, Linux, AWS',
 'DevOps, Terraform, Kubernetes, Azure, Cloud, Python',
 'Incident Response, Cloud, DevSecOps, Terraform, English, AWS',
 'Azure, Docker, Cloud, AWS, DevOps, English',
 'Cloud, GCP, VMware, Azure, AWS, CloudFormation',
 'Cloud, Networking, Azure, Endpoint Protection, Firewall, Security',
 'System Architecture, Python, Kubernetes, Docker, Cloud, Linux',
 'AWS, Terraform, Cloud-native Architecture, Azure, DevOps, English',
 'Product Management, Design Systems, Agile, SQL, Database, Cloud',
 'AWS, Cloud, Kubernetes',
 'MySQL, AWS',
 'AWS, AWS Lambda, Linux, Azure, JavaScript, SQL',
 'CloudFormation, CI/CD, Terraform, AWS',
 'Security, IT Governance, Governance, Risk & Compliance, Cloud Security, Information Security',
 'Application Security, C language, Cloud-native Architecture, C++, iOS, Android',
 'DevOps, Python, CI/CD, Cloud, Docker, Kubernetes',
 'Project Management, English, Google Cloud, Azure, AWS',
 'Cloud Security, AWS CloudFormation, Linux',
 'DevSecOps, Cloud Security, Information Security, Cybersecurity, AWS, Identity & Access Management',
 'AI, Cloud, LLM, Java, Python, .NET',
 'QA QC, VMware, Automation Test, Tester, Cloud, English',
 'Application Security, Microservices, API, DevSecOps, Cloud Security',
 'Business Analysis, Windows, Microsoft Dynamics 365, English, Security, Cloud',
 'System Architecture, System Admin, Cloud Security, GCP, AWS, Networking',
 'Automation Test, Google Cloud, JavaScript, C++, Python',
 'Cloud, English',
 'Java, ReactJS, JavaScript, Cloud, AI, Spring Boot',
 'Java, Solution Architecture, API, Docker, Cloud',
 'Cloud, Kubernetes, DevOps, Scrum, English',
 'Java, Microservices, Azure, Spring Boot, Cloud, Spring',
 'Python, Cloud, AWS, Machine Learning, AI, C++',
 'DevOps, CI/CD, Networking, Cloud, AWS, Python',
 'Java, Kafka, Cloud, Microservices, Kubernetes, Python',
 'DevSecOps, DevOps, Git, Python, CI/CD, AWS',
 'Golang, Kafka, Cloud, CI/CD, OOP',
 'System Admin, Linux, Windows Server, Cloud, SQL, MySQL',
 'System Admin, Cloud, AWS, Linux, Windows Server, System Architecture',
 'DevOps, Python, Docker, CI/CD, Cloud',
 'Linux, Terraform, CI/CD, Docker, Cloud, Windows Server',
 'AI, LLM, MLOps, Cloud, Python, Golang',
 'Application Security, API, OWASP, Cloud Security, Microsoft Azure SQL Database, AWS',
 'DevOps, Terraform, Cloud, Kubernetes, Docker, AWS',
 'Cloud, DevOps, System Admin, Software Architecture, Security, Networking',
 'Microsoft Azure SQL Database, Microsoft SQL Server, Database',
 'DevOps, Terraform, Docker, Linux, Cloud, AWS',
 'Software Architecture, C#, WPF, AI, Solution Architecture, Cloud',
 'DevOps, Kubernetes, Unix, Linux, AWS, Cloud',
 'NodeJS, Cloud, Git, AI, JavaScript, TypeScript',
 'Application Security, Vulnerability Management, DevSecOps, Cloud Security, ISO 27001, English',
 'System Architecture, GCP, Cloud Security, System Admin, Networking, AWS',
 'Software Architecture, ReactJS, NestJS, Cloud, DevOps, NodeJS',
 'Team Management, ERP, Machine Learning, AI, Cloud',
 'DBA, PostgreSql, Database, Cloud, Oracle, SQL',
 'Java, NodeJS, Golang, AI, Cloud, Python',
 'Product Owner, AI, Cloud, Software Architecture, Scrum, Product Management',
 'OutSystems, .NET, Java, English, Database, Cloud',
 'Fullstack, Leadership, AI, Cloud, Kafka, PostgreSql',
 'C#, English, AI, Azure, Cloud, .Net Core',
 'DevOps, System Architecture, Splunk, CI/CD, Grafana, Cloud',
 'Fullstack, Cloud Security, NumPy, Pandas, AI, Python',
 'IT Support, Cloud, Security, English, Microsoft Dynamics 365, Windows',
 'CompTIA Network+, Cisco, Cloud, AWS, Networking, Python',
 'System Admin, Cloud, Linux, Microsoft SQL Server, Oracle, Database',
 'QA QC, Networking, Linux, Tester, Cloud, English',
 'AI, MLOps, Database, Cloud, Python, Machine Learning',
 'Software Architecture, Stakeholder management, ServiceNow, DevOps, Cloud',
 'Golang, MongoDB, PostgreSql, Cloud, AWS, NodeJS',
 'Java, C++, Oracle, Cloud, MySQL, Python',
 'DevSecOps, CI/CD, English, SAP, Cloud, DevOps',
 'AI, Leadership, System Architecture, Cloud, Cybersecurity, Networking',
 'DevOps, Docker, English, Azure, AWS, Cloud',
 'Linux, System Admin, Networking, Security, Cloud, English',
 'Java, AWS, Cloud, ReactJS, English',
 'Solution Architecture, Redis, Java, Microservices, Cloud, Oracle',
 'Database, Cloud, MariaDB, English, PostgreSql, SQL',
 'DevSecOps, Docker, English, Cloud, CI/CD',
 'Bridge Engineer, AI, Japanese IT Communication, Team Management',
 'Security, DevSecOps, AWS, Linux, SIEM, CI/CD',
 'Enterprise Architecture, .NET, Spring Boot, Event-Driven Architecture, Microservices, TOGAF',
 'Project Management, MLOps, Azure, Kanban, Scrum, Generative AI',
 'AI, LLM, Deep Learning, Machine Learning, Computer Vision, NLP',
 'Machine Learning, PyTorch, Generative AI',
 'Machine Learning, Python, DevOps, Linux, AI, MLOps',
 'Machine Learning, English, NLP, LLM, Python',
 'AI, ERP, API, Machine Learning',
 'Machine Learning, Algorithms, Data Science, AI, Data Analysis, English',
 'Python, Machine Learning, AI, API, NodeJS',
 'Python, LLM, Flask, FastAPI',
 'AI, LLM, Generative AI, AWS, English',
 'AI, Generative AI',
 'AI, Python, TensorFlow, PyTorch, MLOps',
 'AI, JavaScript, PyTorch, TensorFlow, C++, Python',
 'AI, PyTorch, Python, SQL, Solution Architecture, Machine Learning',
 'AI, Machine Learning, Python, C#, LLM',
 'AI, AWS, Git, English, PyTorch, Machine Learning',
 'AI, NLP, Deep Learning, Python, API, Machine Learning',
 'AI, Machine Learning, NextJS, ReactJS, Python, NodeJS',
 'AI, Redis, AWS, LLM, Python, Machine Learning',
 'AI, LLM, Generative AI, Machine Learning, NLP, Python',
 'AI, Python, LLM, Azure, OCR, Machine Learning',
 'PyTorch, Deep Learning, Machine Learning, AI, Docker, Python',
 'AI, Deep Learning, API, Machine Learning',
 'AI, LLM, Python, Machine Learning',
 'AI, Machine Learning, CI/CD, Python, PyTorch, TensorFlow',
 'AI, Predictive models, Machine Learning, Database, SAP, Python',
 'AI, OCR, PyTorch, Python, Computer Vision, Machine Learning',
 'AI, Machine Learning, Deep Learning, TensorFlow, Python, NLP',
 'AI, SQL, Machine Learning, LLM',
 'AI, JavaScript, PHP, Machine Learning, LLM',
 'Generative AI, English, TensorFlow, PyTorch, Python, LLM',
 'Python, C++',
 'Python, FastAPI, Docker, Microservices Architecture, Golang, C++',
 'Python, TensorFlow, Flask, FastAPI, Microservices, C++',
 'AI, Python, Docker, LLM, Generative AI',
 'AI, Docker, Microservices, Python',
 'Python, Prompt Engineering, Microservices, API, AI, LLM',
 'Python, Java, JavaScript, Git, AI, English',
 'AI, Database, Golang, Java, Python',
 'AI, Azure, JavaScript, Git, C#, Python',
 'NodeJS, Docker, Python, Automation Test, Redis',
 'Generative AI, English, LLM',
 'Python, AWS CloudFormation, MLOps, LLM, scikit-learn, TensorFlow',
 'PyTorch, TensorFlow, NLP, AI, LLM',
 'Python, Keras, TensorFlow, NLP, AI, C++',
 'Python, Agile',
 'AI, Python, Computer Vision, NLP',
 'AI, TensorFlow, PyTorch, Microservices, C++, Python',
 'AI, Flask, Computer Vision, Microservices, C++, Python',
 'Computer Vision, Deep Learning, TensorFlow, PyTorch, Machine Learning, AI',
 'Leadership, Machine Learning, AI, JavaScript, TypeScript, Python',
 'AI, Machine Learning, Deep Learning',
 'C++, Machine Learning, AI, C language, Python, English',
 'Python, English, Docker, FastAPI, Machine Learning, AI',
 'Generative AI, Data Science, Python, Leadership, Machine Learning',
 'Python, Azure, C#, Machine Learning, AI, .NET',
 'React Native, TypeScript, Machine Learning, Redux, JavaScript',
 'Docker, Golang, Python',
 'C++, Embedded, AI',
 'Product Design, Design, AI, UI-UX',
 'Java, Maven, AI, Spring, Oracle, SQL',
 'QA QC, PostgreSql, AI, CI/CD, Tester, Automation Test',
 'Fullstack, AI, Python, NodeJS, NextJS, ReactJS',
 'Java, MQTT, Kafka, Spring, AI, PostgreSql',
 'Java, English, AWS, Python, AI',
 'Computer Vision, OpenCV, TensorFlow, PyTorch, Python, AI',
 'Java, Python, FastAPI, Microservices, AWS, AI',
 'TypeScript, Unit test, MySQL, AI, AWS, PHP',
 'Tester, Unit test, Automation Test, AI, API, QA QC',
 'Ruby, PostgreSql, Ruby on Rails, MySQL, AI',
 'Java, Microservices, AI, English, .NET, J2EE',
 'Fullstack, AI, Blockchain, DevOps, JavaScript, Python',
 'Computer Vision, OpenCV, C++, Python, Deep Learning, AI',
 'Software Architecture, Leadership, AI, AWS, SQL, Python',
 'Security, GCP, Blockchain, AI',
 'VueJS, AI, English, JavaScript, ReactJS',
 'QA QC, Generative AI, Automation Test, Java, Tester, Team Management',
 'Golang, Design Systems, Unit test, AI, AWS, English',
 'Project Management, Data-driven, AI',
 '.NET, ReactJS, AI, SQL, PostgreSql, NextJS',
 'JavaScript, AI, Leadership, React Native, ReactJS, NodeJS',
 'Tester, Agile, API, Mobile Apps, AI, QA QC',
 'MLOps, Docker, Project Management, Business Analysis, English, Python',
 'CompTIA Network+, Networking',
 'Fullstack, Kotlin, Swift, Mobile Apps, React Native, Flutter',
 'Software Architecture, AI, Angular, .NET, Microservices, Azure',
 'Software Architecture, LLM, English, AI',
 'Python, AI, AWS, DevOps, Software Architecture',
 'Python, Golang',
 'ReactJS, NextJS, React Native, TypeScript, AI',
 'Golang, Microservices Architecture, Kubernetes, ReactJS, PostgreSql, AI',
 'Product Management, LLM, Data-driven, English, PRD, AI',
 'Robotic Process Automation (RPA), Power Automate, Azure, AI, Python, English',
 'Embedded, Clean Architecture, AI, Linux, C++, Qt',
 '.NET, English, Xamarin, Android, iOS, AI',
 'AI, Product Metrics, Business Analysis, LLM, Product strategy, Product Management',
 'Golang, Kafka, Microservices, AI, AWS, MySQL',
 'Java, AI, Solution Architecture, Microservices, Spring, OOP',
 'Project Management, SAP, Agile, English, AI',
 'Product Owner, Project Management, Product Management, AI, Blockchain, Team Management',
 'ReactJS, PostgreSql, AI, API, NodeJS, JavaScript',
 'Fullstack, CI/CD, ReactJS, AI, NodeJS, JavaScript',
 'Product Management, Data-driven, LLM, English, PRD, AI',
 'PHP, GitHub, Laravel, MVC, AI, JavaScript',
 'Automation Test, AI, Agile, JavaScript, CI/CD, API',
 'Golang, ERP, Docker, Generative AI, English',
 'Fullstack, AI, CI/CD, SQL, NodeJS, ReactJS',
 'iOS, OOP, AI, MVC, Swift, MVVM',
 'QA QC, Automation Test, Tester, AI, English',
 '.NET, Automation Test, ReactJS, C#, AI, English',
 'Java, Golang, Spring Boot, MySQL, AI, Oracle',
 'Python, API, AI, SQL, OOP, Django',
 'React Native, TypeScript, English, AI',
 'Embedded, AI, Cisco, CI/CD, C++, Python',
 'Design, AI, Figma, CSS, HTML',
 'Games, System Architecture, Cocos Creator, TypeScript, Unity, AI',
 'JavaScript, Product Management, Generative AI, NodeJS, ReactJS',
 'ReactJS, AI, HTML, NextJS, TypeScript, JavaScript',
 'Mobile Apps, English, AI, Flutter, iOS, Android',
 'UI-UX, Design Systems, Usability testing, User journey, AI, Figma',
 'Project Management, AI, Software Architecture, Stakeholder management, Agile',
 'Java, AI, SQL, Oracle, Spring',
 '.NET, AI, VueJS, C#, Azure, ASP.NET',
 'ReactJS, Agile, 3ds Max, AI, NextJS',
 'ReactJS, JavaScript, TypeScript, AI, English',
 'VueJS, JavaScript, Angular, ReactJS, AI, TypeScript',
 'UI-UX, Scrum, Figma, AI, Design, Agile',
 'Java, MySQL, MongoDB, AI, Spring, Microservices',
 'Flutter, English, React Native, Swift, Product Management, Software Architecture',
 'Automation Test, API, QA QC, Tester, CI/CD, Playwright',
 'Java, Spring Boot',
 'ReactJS, VueJS, JavaScript, Tailwind, CSS, HTML',
 'UI-UX, Visual Design, Product Design, Figma, Mobile Apps, English',
 'Product Design, UI-UX',
 'Database, PostgreSql, Python, MongoDB, MySQL, AWS',
 'Database, SQL',
 'Database, System Admin, MongoDB, MySQL, Data Analysis, SQL',
 'Database, SQL, Unix, Oracle',
 'Tester, CI/CD, Scrum, Agile, Database, API',
 'Database, PostgreSql, DBA',
 'System Admin, Networking, Database, Incident Response, SQL, IT Support',
 '.NET, DevOps, Microsoft Azure SQL Database, CI/CD, C#, Microservices',
 'Tester, Agile, CI/CD, Web API, Database, API',

In [9]:
# Cột job_expertise (chuyên môn công việc) có bao nhiêu giá trị duy nhất
df['job_expertise'].unique().tolist()

['Data Analyst',
 'BI Analyst / BI Developer',
 'Data Engineer',
 'Business Analyst',
 'Manager',
 'Project Manager',
 'Mobile Application Developer',
 'Big Data Engineer',
 'Data Scientist',
 'Data Architect',
 'Data Governance Specialist',
 'Product Owner',
 'Compliance Officer / Analyst',
 'Banking & Financial Systems Developer',
 'Solution Architect',
 'Automation Tester',
 'AI / Machine Learning Engineer',
 'Database Engineer',
 'Fullstack Developer',
 'Backend Developer',
 'Cloud Engineer',
 'Network Engineer',
 'Systems Engineer / Administrator',
 'Product Manager',
 'Security Engineer',
 'DevOps Engineer',
 'DevSecOps Engineer',
 'Application Security Engineer',
 'Field Support',
 'Software/Technical Architect',
 'Database Administrator',
 'Low-Code/No-Code Developer',
 'IT Support',
 'Manual Tester',
 'IT Administrator',
 'Bridge System Engineer (BrSE)',
 'Enterprise Architect',
 'Scrum Master / Agile Coach',
 'Computer Vision Engineer',
 'AI Researcher',
 'Blockchain Developer',
 'AI Architect',
 'Product Designer',
 'Software Engineer in Test (SDET)',
 'Frontend Developer',
 'RPA Engineer',
 'Embedded Engineer',
 'Test Coordinator / QAQC Coordinator',
 'Game Developer',
 'UX/UI Designer',
 'ERP Consultant',
 'Process Quality Assurance (PQA)',
 'UX Researcher',
 'IT Consultant',
 'ERP Developer',
 'IT Helpdesk',
 'GRC Specialist',
 'Enterprise Application Consultant (CRM / HCM / SCM and other enterprise solutions)',
 'DataOps / MLOps Engineer',
 'IT Auditor / IT Risk Manager',
 'SysOps Engineer',
 'C-level (CTO, CIO, CISO, CDO)',
 'Integration & Legacy Systems Developer',
 'IoT Application Developer',
 'Hardware-Software Integration Engineer',
 'Site Reliability Engineer (SRE)']

In [ ]:
# Cột job_domain có bao nhiêu giá trị duy nhất
df['job_domain'].unique().tolist()

['Materials and Mining',
 'Banking, Financial Services',
 'Software Products and Web Services',
 'E-commerce, Software Products and Web Services',
 'Education and Training',
 'E-commerce, IT Services and IT Consulting, Software Products and Web Services, AI Software & Services',
 'Sports and Fitness',
 'Telecommunication',
 'Retail and Wholesale',
 'Transportation, Logistics and Warehouse, Financial Services',
 'IT Services and IT Consulting',
 'Banking, IT Services and IT Consulting, Telecommunication, Emerging Tech R&D, AI Software & Services',
 'Game, IT Services and IT Consulting',
 'Software Products and Web Services, Healthcare',
 'Software Development Outsourcing',
 'Tourism and Hospitality Services',
 'Banking, IT Services and IT Consulting',
 'Banking, Securities & Investment, Financial Services, AI Software & Services',
 'IT Services and IT Consulting, Financial Services',
 'Banking, Software Development Outsourcing',
 'E-commerce',
 'Trading and Commercial, Agriculture',
 'Consumer Goods',
 'IT Services and IT Consulting, Software Products and Web Services',
 'Banking, Software Products and Web Services',
 'Healthcare',
 'E-commerce, Transportation, Logistics and Warehouse, Software Products and Web Services',
 'Government, IT Services and IT Consulting',
 'Banking, Transportation, Logistics and Warehouse, Software Development Outsourcing, Software Products and Web Services, Financial Services',
 'Banking',
 'Securities & Investment',
 'IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services',
 'Banking, Software Products and Web Services, Financial Services',
 'Transportation, Logistics and Warehouse',
 'Insurance, Banking, Securities & Investment, Financial Services',
 'Financial Services',
 'Software Products and Web Services, Healthcare, Financial Services',
 'Government, Software Products and Web Services',
 'IT Hardware and Computing',
 'Emerging Tech R&D',
 'Banking, IT Services and IT Consulting, Software Products and Web Services, Financial Services, AI Software & Services',
 'E-commerce, Software Products and Web Services, AI Software & Services',
 'Banking, IT Services and IT Consulting, AI Software & Services',
 'Insurance, Banking, Software Products and Web Services, Financial Services',
 'Government, Network and Infrastructure, AI Software & Services',
 'IT Hardware and Computing, Network and Infrastructure, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'E-commerce, Transportation, Logistics and Warehouse',
 'Software Products and Web Services, AI Software & Services',
 'Consumer Goods, Manufacturing and Engineering, Retail and Wholesale, Transportation, Logistics and Warehouse, Network and Infrastructure',
 'AI Software & Services',
 'Software Products and Web Services, Financial Services',
 'Banking, IT Services and IT Consulting, Software Development Outsourcing, Financial Services',
 'Insurance, Banking, Financial Services',
 'Food and Beverage, IT Services and IT Consulting',
 'E-commerce, Media, Advertising and Entertainment, Software Products and Web Services',
 'Insurance, IT Services and IT Consulting, Healthcare, Financial Services, AI Software & Services',
 'IT Services and IT Consulting, AI Software & Services',
 'Network and Infrastructure',
 'IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, Professional Services, AI Software & Services',
 'IT Services and IT Consulting, Software Products and Web Services, Securities & Investment, Financial Services',
 'Real Estate, Property and Construction',
 'IT Hardware and Computing, IT Services and IT Consulting, Software Products and Web Services, AI Software & Services',
 'Manufacturing and Engineering, IT Services and IT Consulting, Cyber Security, Software Development Outsourcing, Software Products and Web Services',
 'IT Services and IT Consulting, Cyber Security',
 'Blockchain & Web3 Services',
 'Banking, IT Services and IT Consulting, Financial Services',
 'E-commerce, Transportation, Logistics and Warehouse, Cyber Security, Network and Infrastructure, Software Development Outsourcing',
 'Insurance',
 'IT Services and IT Consulting, Software Products and Web Services, Professional Services',
 'Cyber Security',
 'Banking, IT Services and IT Consulting, Software Products and Web Services',
 'Banking, IT Services and IT Consulting, Software Products and Web Services, Financial Services',
 'Insurance, E-commerce, Banking, Healthcare, Financial Services',
 'Software Development Outsourcing, AI Software & Services',
 'Banking, Software Products and Web Services, Financial Services, AI Software & Services',
 'Creative and Design',
 'Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'IT Services and IT Consulting, Cyber Security, Software Products and Web Services, Emerging Tech R&D, AI Software & Services',
 'Insurance, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Software Products and Web Services, Facility Management',
 'Banking, Securities & Investment, Financial Services, Emerging Tech R&D',
 'Manufacturing and Engineering',
 'Cyber Security, Software Products and Web Services, AI Software & Services',
 'Software Development Outsourcing, Software Products and Web Services',
 'E-commerce, Media, Advertising and Entertainment, IT Services and IT Consulting, Software Products and Web Services',
 'IT Hardware and Computing, Cyber Security, Software Products and Web Services, AI Software & Services',
 'IT Hardware and Computing, Software Products and Web Services, AI Software & Services',
 'IT Services and IT Consulting, Software Products and Web Services, Emerging Tech R&D, AI Software & Services',
 'Blockchain & Web3 Services, IT Hardware and Computing, IT Services and IT Consulting, AI Software & Services',
 'Media, Advertising and Entertainment',
 'IT Hardware and Computing, IT Services and IT Consulting, AI Software & Services',
 'E-commerce, IT Services and IT Consulting, Transportation, Logistics and Warehouse, Software Development Outsourcing, Software Products and Web Services',
 'Tourism and Hospitality Services, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Tourism and Hospitality Services, IT Services and IT Consulting, Software Products and Web Services, Emerging Tech R&D, AI Software & Services',
 'IT Services and IT Consulting, Software Products and Web Services, AI Software & Services',
 'Real Estate, Property and Construction, IT Services and IT Consulting, Software Products and Web Services',
 'Media, Advertising and Entertainment, IT Services and IT Consulting, Software Products and Web Services, Emerging Tech R&D, AI Software & Services',
 'Blockchain & Web3 Services, Software Products and Web Services, AI Software & Services',
 'E-commerce, Pharmaceuticals, Retail and Wholesale, Healthcare, AI Software & Services',
 'Education and Training, Software Products and Web Services',
 'Food and Beverage, Consumer Goods, E-commerce, Retail and Wholesale, Software Products and Web Services',
 'Blockchain & Web3 Services, Real Estate, Property and Construction, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Blockchain & Web3 Services, AI Software & Services',
 'Real Estate, Property and Construction, Software Products and Web Services',
 'Software Products and Web Services, Healthcare, AI Software & Services',
 'Blockchain & Web3 Services, IT Services and IT Consulting, Software Products and Web Services',
 'Transportation, Logistics and Warehouse, Software Products and Web Services',
 'IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, Emerging Tech R&D, AI Software & Services',
 'Software Products and Web Services, Financial Services, AI Software & Services',
 'IT Hardware and Computing, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'IT Services and IT Consulting, Transportation, Logistics and Warehouse, Software Products and Web Services, AI Software & Services',
 'Insurance, E-commerce, Banking, IT Services and IT Consulting, Software Development Outsourcing',
 'Consumer Goods, IT Services and IT Consulting, Transportation, Logistics and Warehouse',
 'Tourism and Hospitality Services, IT Hardware and Computing, IT Services and IT Consulting, Software Products and Web Services',
 'IT Services and IT Consulting, Software Products and Web Services, Sports and Fitness',
 'IT Hardware and Computing, Telecommunication, Utilities, Emerging Tech R&D, AI Software & Services',
 'Trading and Commercial',
 'Game, Media, Advertising and Entertainment, Software Products and Web Services, Creative and Design, AI Software & Services',
 'Creative and Design, AI Software & Services',
 'Software Products and Web Services, Creative and Design',
 'Software Products and Web Services, Sports and Fitness, AI Software & Services',
 'Blockchain & Web3 Services, Software Development Outsourcing',
 'E-commerce, Media, Advertising and Entertainment',
 'IT Services and IT Consulting, Transportation, Logistics and Warehouse, Software Products and Web Services, Creative and Design, AI Software & Services',
 'Game',
 'Banking, Securities & Investment, Financial Services',
 'IT Services and IT Consulting, Transportation, Logistics and Warehouse',
 'IT Hardware and Computing, IT Services and IT Consulting, Transportation, Logistics and Warehouse, Cyber Security, Software Products and Web Services',
 'Manufacturing and Engineering, Software Products and Web Services',
 'Software Development Outsourcing, Software Products and Web Services, Financial Services, AI Software & Services',
 'IT Hardware and Computing, Manufacturing and Engineering, IT Services and IT Consulting, Software Products and Web Services',
 'E-commerce, IT Services and IT Consulting, Software Products and Web Services',
 'Manufacturing and Engineering, AI Software & Services',
 'IT Services and IT Consulting, Securities & Investment, Financial Services',
 'Game, IT Hardware and Computing',
 'Banking, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Consumer Goods, IT Services and IT Consulting, Apparel and Fashion',
 'Insurance, Banking, IT Services and IT Consulting',
 'E-commerce, Software Products and Web Services, Financial Services',
 'Banking, Government, IT Services and IT Consulting, Software Development Outsourcing',
 'E-commerce, IT Services and IT Consulting, Software Products and Web Services, Professional Services, AI Software & Services',
 'Insurance, Banking, IT Services and IT Consulting, Healthcare, Financial Services',
 'Software Products and Web Services, Agriculture, Emerging Tech R&D, AI Software & Services',
 'Transportation, Logistics and Warehouse, Software Products and Web Services, AI Software & Services',
 'Blockchain & Web3 Services, Real Estate, Property and Construction, AI Software & Services',
 'E-commerce, Game, Software Products and Web Services',
 'IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Manufacturing and Engineering, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Real Estate, Property and Construction, Financial Services',
 'Securities & Investment, Financial Services',
 'Tourism and Hospitality Services, IT Services and IT Consulting, Software Products and Web Services, AI Software & Services',
 'IT Services and IT Consulting, Transportation, Logistics and Warehouse, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Real Estate, Property and Construction, Transportation, Logistics and Warehouse, Software Products and Web Services',
 'Food and Beverage',
 'Game, Software Products and Web Services, AI Software & Services',
 'IT Services and IT Consulting, Cyber Security, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'IT Services and IT Consulting, Network and Infrastructure',
 'Blockchain & Web3 Services, Banking, Software Products and Web Services, Securities & Investment, Financial Services',
 'Insurance, Banking, Software Development Outsourcing, Financial Services, AI Software & Services',
 'IT Hardware and Computing, IT Services and IT Consulting, Network and Infrastructure, Software Products and Web Services',
 'Insurance, Banking, Retail and Wholesale, Securities & Investment, Financial Services',
 'Insurance, Software Products and Web Services, AI Software & Services',
 'E-commerce, IT Services and IT Consulting',
 'E-commerce, Banking, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services',
 'Banking, Real Estate, Property and Construction, IT Services and IT Consulting, Network and Infrastructure, Software Products and Web Services',
 'Banking, IT Services and IT Consulting, Cyber Security, Network and Infrastructure, Software Products and Web Services',
 'Banking, Financial Services, AI Software & Services',
 'E-commerce, Trading and Commercial, Creative and Design, AI Software & Services',
 'IT Services and IT Consulting, Emerging Tech R&D, AI Software & Services',
 'Blockchain & Web3 Services, Banking, IT Services and IT Consulting, Software Products and Web Services, Financial Services',
 'Retail and Wholesale, Transportation, Logistics and Warehouse, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Game, Media, Advertising and Entertainment, Software Products and Web Services',
 'Cyber Security, Securities & Investment',
 'Telecommunication, Network and Infrastructure, Emerging Tech R&D',
 'E-commerce, Software Development Outsourcing, Software Products and Web Services, Sports and Fitness, AI Software & Services',
 'Telecommunication, Software Products and Web Services',
 'Insurance, Pharmaceuticals, IT Services and IT Consulting, Trading and Commercial, Healthcare',
 'Tourism and Hospitality Services, Real Estate, Property and Construction, Software Products and Web Services',
 'Banking, Network and Infrastructure',
 'Education and Training, AI Software & Services',
 'Financial Services, AI Software & Services',
 'Banking, IT Hardware and Computing, IT Services and IT Consulting, Cyber Security, Financial Services',
 'E-commerce, IT Services and IT Consulting, Transportation, Logistics and Warehouse, Software Products and Web Services',
 'Apparel and Fashion',
 'Food and Beverage, E-commerce, Transportation, Logistics and Warehouse, Agriculture, Healthcare',
 'IT Services and IT Consulting, Transportation, Logistics and Warehouse, Software Products and Web Services, Emerging Tech R&D, AI Software & Services',
 'IT Hardware and Computing, Real Estate, Property and Construction, Materials and Mining',
 'Software Development Outsourcing, Staffing and Recruiting, Healthcare, AI Software & Services',
 'Tourism and Hospitality Services, Insurance, E-commerce, Education and Training, Game',
 'IT Services and IT Consulting, Network and Infrastructure, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Government, Securities & Investment',
 'Pharmaceuticals',
 'IT Services and IT Consulting, Software Products and Web Services, Utilities',
 'Food and Beverage, IT Services and IT Consulting, Software Development Outsourcing, Agriculture, Healthcare',
 'Banking, Real Estate, Property and Construction, IT Services and IT Consulting, Financial Services',
 'IT Services and IT Consulting, Transportation, Logistics and Warehouse, Software Products and Web Services',
 'Banking, Telecommunication, Financial Services',
 'Agriculture',
 'Manufacturing and Engineering, Transportation, Logistics and Warehouse',
 'Government',
 'Cyber Security, Network and Infrastructure',
 'Insurance, Banking, Cyber Security, Securities & Investment, Financial Services',
 'E-commerce, IT Services and IT Consulting, Cyber Security, Network and Infrastructure, Software Products and Web Services',
 'IT Services and IT Consulting, Software Development Outsourcing, AI Software & Services',
 'Real Estate, Property and Construction, AI Software & Services',
 'E-commerce, IT Services and IT Consulting, Telecommunication, Software Products and Web Services, Creative and Design',
 'E-commerce, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, AI Software & Services',
 'Banking, IT Services and IT Consulting, Software Development Outsourcing, Software Products and Web Services, Financial Services',
 'E-commerce, Retail and Wholesale, IT Services and IT Consulting, Network and Infrastructure, Software Products and Web Services',
 'E-commerce, Banking, Government, IT Services and IT Consulting, Financial Services',
 'IT Services and IT Consulting, Network and Infrastructure, Software Development Outsourcing, Software Products and Web Services',
 'Education and Training, IT Services and IT Consulting, Network and Infrastructure, Software Products and Web Services, Professional Services',
 'Tourism and Hospitality Services, IT Services and IT Consulting, Software Development Outsourcing',
 'Consumer Goods, E-commerce, Retail and Wholesale, IT Services and IT Consulting, Financial Services',
 'E-commerce, IT Services and IT Consulting, Software Products and Web Services, Emerging Tech R&D, AI Software & Services',
 'Blockchain & Web3 Services, IT Services and IT Consulting, Software Products and Web Services, Financial Services, AI Software & Services',
 'Blockchain & Web3 Services, Consumer Goods, E-commerce, Banking, IT Services and IT Consulting',
 'Banking, IT Services and IT Consulting, Software Development Outsourcing',
 'E-commerce, Real Estate, Property and Construction, IT Services and IT Consulting, Software Products and Web Services, Emerging Tech R&D',
 'Media, Advertising and Entertainment, IT Services and IT Consulting',
 'IT Services and IT Consulting, Network and Infrastructure, Software Products and Web Services, Professional Services, AI Software & Services']

In [11]:
# Cột company_industry có bao nhiêu giá trị duy nhất
df['company_industry'].unique().tolist()

['Materials and Mining',
 'Banking',
 'Software Products and Web Services',
 'E-commerce',
 'Education and Training',
 'Sports and Fitness',
 'IT Hardware and Computing',
 'Retail and Wholesale',
 'Financial Services',
 'Transportation, Logistics and Warehouse',
 'IT Services and IT Consulting',
 'Healthcare',
 'Software Development Outsourcing',
 'Telecommunication',
 'Trading and Commercial',
 'Consumer Goods',
 'Securities & Investment',
 'Creative and Design',
 'Manufacturing and Engineering',
 'Insurance',
 'AI Software & Services',
 'Food and Beverage',
 'Media, Advertising and Entertainment',
 'Professional Services',
 'Real Estate, Property and Construction',
 'Staffing and Recruiting',
 nan,
 'Cyber Security',
 'Tourism and Hospitality Services',
 'Game',
 'Pharmaceuticals',
 'Environment',
 'Utilities',
 'Apparel and Fashion',
 'Agriculture']

In [12]:
# Cột company_type có bao nhiêu giá trị duy nhất
df['company_type'].unique().tolist()

['IT Outsourcing',
 'IT Product',
 'Non-IT',
 'IT Service and IT Consulting',
 'Headhunt']

In [13]:
# Cột company_country có bao nhiêu giá trị duy nhất
df['company_country'].unique().tolist()

['Vietnam',
 'France',
 'Australia',
 'China',
 'Singapore',
 'United Kingdom',
 'United States',
 'Czechia',
 'Switzerland',
 'Netherlands',
 'South Korea',
 'Germany',
 'Japan',
 'Denmark',
 'Philippines',
 'Taiwan',
 'Sweden',
 'Canada',
 'India',
 'Hong Kong',
 'United Arab Emirates',
 'Portugal',
 'Malaysia',
 'Belgium',
 'Norway',
 "Lao People's Democratic Republic"]